// Command contractgen projects the adapter's Go declarations into its Python artifacts.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/MiniMax-AI/OpenAgentCore/internal/agentnetwork"
	"github.com/MiniMax-AI/OpenAgentCore/internal/runtimebootstrap"
	"github.com/MiniMax-AI/OpenAgentCore/services/core/internal/sandbox"
	"github.com/MiniMax-AI/OpenAgentCore/services/core/internal/sandbox/e2b"
)

func main() {
	check := flag.Bool("check", false, "reject stale projections")
	flag.Parse()
	root, err := os.Getwd()
	must(err)
	for {
		if _, err := os.Stat(filepath.Join(root, "go.mod")); err == nil {
			break
		}
		parent := filepath.Dir(root)
		if parent == root {
			panic("repository root not found")
		}
		root = parent
	}
	write := func(name string, data []byte) {
		path := filepath.Join(root, name)
		if *check {
			actual, err := os.ReadFile(path)
			must(err)
			if !bytes.Equal(actual, data) {
				panic("stale projection: " + name + "; run go generate ./services/core/internal/sandbox/e2b")
			}
		} else {
			must(os.WriteFile(path, data, 0644))
		}
	}
	lock, err := os.ReadFile(filepath.Join(root, "services/core/tools/e2b-provider/requirements.lock"))
	must(err)
	pin := regexp.MustCompile(`(?m)^e2b==([0-9]+\.[0-9]+\.[0-9]+) `).FindSubmatch(lock)
	if len(pin) != 2 {
		panic("expected exactly pinned e2b lock entry")
	}
	sdk := string(pin[1])
	for _, name := range []string{"services/core/tools/e2b-provider/requirements.in", "services/core/deploy/e2b/requirements.txt"} {
		data, err := os.ReadFile(filepath.Join(root, name))
		must(err)
		if !regexp.MustCompile(`(?m)^e2b==` + regexp.QuoteMeta(sdk) + `$`).Match(data) {
			panic("SDK pin differs from lock: " + name)
		}
	}
	goCode, err := format.Source([]byte("// Code generated by contractgen; DO NOT EDIT.\npackage e2b\nconst SDKVersion = " + strconv.Quote(sdk) + "\n"))
	must(err)
	write("services/core/internal/sandbox/e2b/helper_sdk_generated.go", goCode)
	bootstrap := fields(reflect.TypeFor[sandbox.Bootstrap]())
	bootstrap = slices.DeleteFunc(bootstrap, func(s string) bool { return s == "CoreURL" || s == "Credential" })
	bootstrap = append(bootstrap, "InstallationID", "RuntimeBootstrap")
	identity := fields(reflect.TypeFor[sandbox.Reference]())
	for _, name := range []string{"SessionID", "DeviceID"} {
		if !slices.Contains(bootstrap, name) {
			panic("bootstrap identity field missing: " + name)
		}
		identity = append(identity, name)
	}
	identity = append(identity, "InstallationID")
	values := map[string]any{
		"PROTOCOL_VERSION": e2b.ProtocolVersion, "SDK_VERSION": sdk,
		"SUSPEND_CONTROL_FILE": runtimebootstrap.SuspendControlFile,
		"MAX_REQUEST":          e2b.MaxRequestBytes, "MAX_RESPONSE": e2b.MaxResponseBytes,
		"MAX_OUTPUT": e2b.MaxOutputBytes, "MAX_COMMAND_INPUT": e2b.MaxCommandInputBytes,
		"MAX_OBSERVATION_REFERENCES": e2b.MaxObservationReferences, "MAX_CREDENTIAL_REFERENCES": e2b.MaxCredentialReferences,
		"OPERATIONS": e2b.HelperOperations(), "ERROR_CODES": e2b.HelperErrors(),
		"REQUEST_FIELDS": fields(reflect.TypeFor[e2b.Request]()), "RESPONSE_FIELDS": fields(reflect.TypeFor[e2b.Response]()),
		"REFERENCE_FIELDS":         fields(reflect.TypeFor[sandbox.Reference]()),
		"COMPUTE_FIELDS":           fields(reflect.TypeFor[sandbox.Compute]()),
		"RETAINED_FIELDS":          fields(reflect.TypeFor[sandbox.RetainedState]()),
		"SUSPEND_FIELDS":           fields(reflect.TypeFor[sandbox.SuspendRequest]()),
		"RESUME_FIELDS":            fields(reflect.TypeFor[sandbox.ResumeRequest]()),
		"MANAGED_BOOTSTRAP_FIELDS": bootstrap, "MANAGED_IDENTITY_FIELDS": identity,
		"NETWORK_ACCESS": networkValues(filepath.Join(root, "internal/agentnetwork/policy.go")),
	}
	var python bytes.Buffer
	python.WriteString("# Code generated by contractgen; DO NOT EDIT.\n\"\"\"Adapter-private wire declarations. No SDK or repository dependency.\"\"\"\n")
	names := make([]string, 0, len(values))
	for name := range values {
		names = append(names, name)
	}
	slices.Sort(names)
	for _, name := range names {
		data, err := json.Marshal(values[name])
		must(err)
		fmt.Fprintf(&python, "%s = %s\n", name, data)
	}
	for _, directory := range []string{"services/core/tools/e2b-provider", "services/core/deploy/e2b"} {
		write(directory+"/helper_contract_generated.py", python.Bytes())
	}
	write("services/core/tools/e2b-provider/testdata/contract.json", fixtures())
}

// Exchanges originate in the Go wire types. Mutations exercise the same invalid
// envelopes and managed bootstrap inputs in both implementations.
func fixtures() []byte {
	r := sandbox.Reference{TenantID: "11111111-1111-4111-8111-111111111111", EnvironmentID: "22222222-2222-4222-8222-222222222222", AllocationID: "33333333-3333-4333-8333-333333333333"}
	b := sandbox.Bootstrap{Reference: r, SessionID: "44444444-4444-4444-8444-444444444444", DeviceID: "55555555-5555-4555-8555-555555555555", CoreURL: "https://core.example/api/v1", Credential: "fixture-only", NetworkAccess: "enabled"}
	installation := "66666666-6666-4666-8666-666666666666"
	connection := b.RuntimeConnection()
	q := e2b.Request{Version: e2b.ProtocolVersion, Operation: "create", Config: e2b.Config{InstallationID: installation}, Reference: r, Bootstrap: &b, RuntimeBootstrap: &connection, Deadline: time.Date(2099, 1, 1, 0, 0, 0, 0, time.UTC)}
	var cases []map[string]any
	add := func(kind, name string, valid bool, payload any) {
		cases = append(cases, map[string]any{"kind": kind, "name": name, "valid": valid, "payload": payload})
	}
	object := func(value any) map[string]any {
		data, err := json.Marshal(value)
		must(err)
		var result map[string]any
		must(json.Unmarshal(data, &result))
		return result
	}
	for _, operation := range e2b.HelperOperations() {
		copy := q

		copy.Operation = operation
		c := sandbox.Compute{Name: r.AllocationID, ID: "native-fixture"}
		retained := sandbox.RetainedState{Reference: r.AllocationID, ID: installation, OperationID: installation, SourceName: c.Name, SourceID: c.ID, Data: "opaque"}
		switch operation {
		case "compute_info", "compute_renew", "compute_kill", "compute_command", "resume_compute":
			copy.Compute = &c
			if operation == "compute_command" {
				copy.Command = &sandbox.Command{Args: []string{"true"}}
			}
		case "suspend":
			copy.Suspend = &sandbox.SuspendRequest{Reference: r, OperationID: installation, Source: c}
		case "resume":
			target := sandbox.Compute{Generation: 1, Name: c.Name, ID: c.ID, RestoredFrom: &retained}
			copy.Resume = &sandbox.ResumeRequest{Reference: r, OperationID: installation, Retained: retained, Target: target}
		case "delete_retained":
			copy.Retained = &retained
		}
		if operation == "observe" || operation == "verify_credential" {
			copy.References = []sandbox.Reference{r}
		}
		add("request", operation, true, copy)
	}
	for _, item := range []struct {
		name, field string
		value       any
	}{
		{"version-null", "Version", nil}, {"version-bool", "Version", true}, {"version-string", "Version", "1"}, {"version-unknown", "Version", e2b.ProtocolVersion + 1},
		{"operation-null", "Operation", nil}, {"operation-unknown", "Operation", "unsupported"}, {"extra", "Extra", true},
		{"reference-null", "Reference", nil}, {"reference-type", "Reference", "invalid"}, {"config-null", "Config", nil},
	} {
		value := object(q)
		value[item.field] = item.value
		add("request", item.name, false, value)
	}
	for _, operation := range []string{"observe", "verify_credential"} {
		limit := e2b.MaxObservationReferences
		if operation == "verify_credential" {
			limit = e2b.MaxCredentialReferences
		}
		for _, count := range []int{0, limit, limit + 1} {
			copy := q
			copy.Operation = operation
			copy.References = make([]sandbox.Reference, count)
			for index := range copy.References {
				copy.References[index] = r
				copy.References[index].AllocationID = fmt.Sprintf("%08x-3333-4333-8333-333333333333", index+1)
			}
			add("request", fmt.Sprintf("%s-count-%d", operation, count), count <= limit && (operation != "observe" || count > 0), copy)
		}
		for _, refs := range []any{map[string]any{}, "invalid", []any{nil}} {
			value := object(q)
			value["Operation"] = operation
			value["References"] = refs
			add("request", operation+"-references-type", false, value)
		}
	}
	duplicate := q
	duplicate.Operation = "observe"
	duplicate.References = []sandbox.Reference{r, r}
	add("request", "duplicate-observation", false, duplicate)
	for _, code := range e2b.HelperErrors() {
		add("response", "error-"+code, true, e2b.Response{Version: e2b.ProtocolVersion, ErrorCode: code})
	}
	for _, item := range []struct {
		field string
		value any
	}{{"Extra", true}, {"Version", true}, {"ErrorCode", "unknown"}, {"ErrorCode", 1}} {
		value := object(e2b.Response{Version: e2b.ProtocolVersion})
		value[item.field] = item.value
		add("response", "invalid-"+item.field, false, value)
	}
	managed := object(b)
	delete(managed, "CoreURL")
	delete(managed, "Credential")
	managed["InstallationID"] = installation
	managed["RuntimeBootstrap"] = runtimebootstrap.Connection(connection)
	for _, policy := range []agentnetwork.Policy{{Access: "enabled"}, {Access: "disabled"}, {Access: "restricted", AllowedDomains: []string{"example.com"}}} {
		value := object(managed)
		value["NetworkAccess"] = policy.Access
		value["AllowedDomains"] = policy.AllowedDomains
		add("managed", policy.Access, true, value)
	}
	for _, item := range []struct {
		field string
		value any
	}{{"Extra", true}, {"DeviceID", nil}, {"DeviceID", "invalid"}, {"NetworkAccess", nil}, {"NetworkAccess", "unknown"}, {"NetworkAccess", true}, {"AllowedDomains", "example.com"}, {"AllowedDomains", []any{1}}} {
		value := object(managed)
		value[item.field] = item.value
		add("managed", "invalid-"+item.field, false, value)
	}
	for key := range managed {
		value := object(managed)
		delete(value, key)
		add("managed", "missing-"+key, false, value)
	}
	// Keep fixture ordering deterministic even when a mutation enumerates fields.
	slices.SortStableFunc(cases, func(a, b map[string]any) int {
		return strings.Compare(a["kind"].(string)+a["name"].(string), b["kind"].(string)+b["name"].(string))
	})
	var result bytes.Buffer
	result.WriteString("[\n")
	for i, c := range cases {
		data, err := json.Marshal(c)
		must(err)
		result.Write(data)
		if i+1 < len(cases) {
			result.WriteByte(',')
		}
		result.WriteByte('\n')
	}
	result.WriteString("]\n")
	return result.Bytes()
}

func fields(t reflect.Type) []string {
	var result []string
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if f.Anonymous {
			result = append(result, fields(f.Type)...)
			continue
		}
		name := strings.Split(f.Tag.Get("json"), ",")[0]
		if name == "-" {
			continue
		}
		if name == "" {
			name = f.Name
		}
		result = append(result, name)
	}
	return result
}

// Read only the access switch of Policy.Validate. Unexpected shapes fail rather
// than silently emitting an incomplete enum or interpreting a general validator.
func networkValues(path string) []string {
	f, err := parser.ParseFile(token.NewFileSet(), path, nil, 0)
	must(err)
	var result []string
	for _, d := range f.Decls {
		fn, ok := d.(*ast.FuncDecl)
		if !ok || fn.Name.Name != "Validate" || fn.Recv == nil {
			continue
		}
		for _, statement := range fn.Body.List {
			s, ok := statement.(*ast.SwitchStmt)
			if !ok {
				continue
			}
			tag, ok := s.Tag.(*ast.SelectorExpr)
			if !ok || tag.Sel.Name != "Access" {
				continue
			}
			for _, clause := range s.Body.List {
				for _, value := range clause.(*ast.CaseClause).List {
					literal, ok := value.(*ast.BasicLit)
					if !ok || literal.Kind != token.STRING {
						panic("network access cases must be string literals")
					}
					access, err := strconv.Unquote(literal.Value)
					must(err)
					p := agentnetwork.Policy{Access: access}
					if p.Validate() != nil {
						p.AllowedDomains = []string{"example.com"}
					}
					if p.Validate() != nil || slices.Contains(result, access) {
						panic("invalid network access projection")
					}
					result = append(result, access)
				}
			}
		}
	}
	if len(result) == 0 {
		panic("network access switch not found")
	}
	return result
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
