// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin_history.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminAuditCursor = `-- name: AdminAuditCursor :one
SELECT created_at FROM admin_audit_log WHERE id=$1
`

func (q *Queries) AdminAuditCursor(ctx context.Context, id pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, adminAuditCursor, id)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const listAdminAuditLog = `-- name: ListAdminAuditLog :many
SELECT id, tenant_id, project_id, admin_credential_id, actor_label, action, resource_type, resource_id, request_id, trace_id, created_at FROM admin_audit_log
WHERE ($1::text='' OR project_id::text=$1)
 AND ($2::text='' OR resource_type=$2)
 AND ($3::text='' OR resource_id=$3)
 AND ($4::text='' OR action=$4)
 AND ($5::timestamptz IS NULL OR created_at>=$5)
 AND ($6::timestamptz IS NULL OR created_at<$6)
 AND ($7::timestamptz IS NULL OR (created_at,id)<($7,$8::uuid))
ORDER BY created_at DESC,id DESC LIMIT $9
`

type ListAdminAuditLogParams struct {
	ProjectID     string             `json:"project_id"`
	ResourceType  string             `json:"resource_type"`
	ResourceID    string             `json:"resource_id"`
	Action        string             `json:"action"`
	CreatedAfter  pgtype.Timestamptz `json:"created_after"`
	CreatedBefore pgtype.Timestamptz `json:"created_before"`
	AfterTime     pgtype.Timestamptz `json:"after_time"`
	AfterID       pgtype.UUID        `json:"after_id"`
	PageLimit     int32              `json:"page_limit"`
}

func (q *Queries) ListAdminAuditLog(ctx context.Context, arg ListAdminAuditLogParams) ([]AdminAuditLog, error) {
	rows, err := q.db.Query(ctx, listAdminAuditLog,
		arg.ProjectID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Action,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.AfterTime,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminAuditLog{}
	for rows.Next() {
		var i AdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.AdminCredentialID,
			&i.ActorLabel,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.RequestID,
			&i.TraceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
