// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin_audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAdminAudit = `-- name: InsertAdminAudit :one
INSERT INTO admin_audit_log (id,tenant_id,admin_credential_id,actor_label,action,project_id,resource_type,resource_id,request_id,trace_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
RETURNING id
`

type InsertAdminAuditParams struct {
	ID                pgtype.UUID `json:"id"`
	TenantID          pgtype.UUID `json:"tenant_id"`
	AdminCredentialID string      `json:"admin_credential_id"`
	ActorLabel        string      `json:"actor_label"`
	Action            string      `json:"action"`
	ProjectID         pgtype.UUID `json:"project_id"`
	ResourceType      string      `json:"resource_type"`
	ResourceID        string      `json:"resource_id"`
	RequestID         string      `json:"request_id"`
	TraceID           string      `json:"trace_id"`
}

func (q *Queries) InsertAdminAudit(ctx context.Context, arg InsertAdminAuditParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertAdminAudit,
		arg.ID,
		arg.TenantID,
		arg.AdminCredentialID,
		arg.ActorLabel,
		arg.Action,
		arg.ProjectID,
		arg.ResourceType,
		arg.ResourceID,
		arg.RequestID,
		arg.TraceID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
