// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: environment_setup.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnvironmentSetup = `-- name: CreateEnvironmentSetup :exec
INSERT INTO environment_setups (session_id, contents) VALUES ($1, $2)
`

type CreateEnvironmentSetupParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	Contents  []byte      `json:"contents"`
}

func (q *Queries) CreateEnvironmentSetup(ctx context.Context, arg CreateEnvironmentSetupParams) error {
	_, err := q.db.Exec(ctx, createEnvironmentSetup, arg.SessionID, arg.Contents)
	return err
}

const getEnvironmentSetup = `-- name: GetEnvironmentSetup :one
SELECT f.contents FROM sessions s LEFT JOIN environment_setups f ON s.id = f.session_id
WHERE s.tenant_id = $1 AND s.id = $2 AND s.deleted_at IS NULL
`

type GetEnvironmentSetupParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetEnvironmentSetup(ctx context.Context, arg GetEnvironmentSetupParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getEnvironmentSetup, arg.TenantID, arg.ID)
	var contents []byte
	err := row.Scan(&contents)
	return contents, err
}

const setSessionSetupMetadata = `-- name: SetSessionSetupMetadata :exec
UPDATE sessions SET configuration = jsonb_set(configuration, '{environment}',
    (configuration->'environment') || jsonb_build_object(
        'packages', $2::jsonb,
        'skills', $3::jsonb,
        'plugins', $4::jsonb,
        'capability_directories', $5::jsonb,
        'initialization', true))
WHERE id = $1
`

type SetSessionSetupMetadataParams struct {
	ID                    pgtype.UUID `json:"id"`
	Packages              []byte      `json:"packages"`
	Skills                []byte      `json:"skills"`
	Plugins               []byte      `json:"plugins"`
	CapabilityDirectories []byte      `json:"capability_directories"`
}

func (q *Queries) SetSessionSetupMetadata(ctx context.Context, arg SetSessionSetupMetadataParams) error {
	_, err := q.db.Exec(ctx, setSessionSetupMetadata,
		arg.ID,
		arg.Packages,
		arg.Skills,
		arg.Plugins,
		arg.CapabilityDirectories,
	)
	return err
}
