// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: initial_environment_files.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInitialEnvironmentFile = `-- name: CreateInitialEnvironmentFile :exec
INSERT INTO initial_environment_files (id, session_id, position, path, size_bytes, contents)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateInitialEnvironmentFileParams struct {
	ID        pgtype.UUID `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
	Position  int32       `json:"position"`
	Path      string      `json:"path"`
	SizeBytes int64       `json:"size_bytes"`
	Contents  []byte      `json:"contents"`
}

func (q *Queries) CreateInitialEnvironmentFile(ctx context.Context, arg CreateInitialEnvironmentFileParams) error {
	_, err := q.db.Exec(ctx, createInitialEnvironmentFile,
		arg.ID,
		arg.SessionID,
		arg.Position,
		arg.Path,
		arg.SizeBytes,
		arg.Contents,
	)
	return err
}

const getInitialEnvironmentFile = `-- name: GetInitialEnvironmentFile :one
SELECT f.id, f.session_id, f.position, f.path, f.size_bytes, f.contents FROM initial_environment_files f JOIN sessions s ON s.id = f.session_id
WHERE s.tenant_id = $1 AND f.session_id = $2 AND f.position = $3 AND s.deleted_at IS NULL
`

type GetInitialEnvironmentFileParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	SessionID pgtype.UUID `json:"session_id"`
	Position  int32       `json:"position"`
}

func (q *Queries) GetInitialEnvironmentFile(ctx context.Context, arg GetInitialEnvironmentFileParams) (InitialEnvironmentFile, error) {
	row := q.db.QueryRow(ctx, getInitialEnvironmentFile, arg.TenantID, arg.SessionID, arg.Position)
	var i InitialEnvironmentFile
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Position,
		&i.Path,
		&i.SizeBytes,
		&i.Contents,
	)
	return i, err
}

const getSessionInitializationReady = `-- name: GetSessionInitializationReady :one
SELECT NOT EXISTS (SELECT 1 FROM environments e WHERE e.session_id = s.id AND e.initialization <> 'complete') AS ready
FROM sessions s WHERE s.tenant_id = $1 AND s.id = $2
`

type GetSessionInitializationReadyParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetSessionInitializationReady(ctx context.Context, arg GetSessionInitializationReadyParams) (bool, error) {
	row := q.db.QueryRow(ctx, getSessionInitializationReady, arg.TenantID, arg.ID)
	var ready bool
	err := row.Scan(&ready)
	return ready, err
}

const setSessionInitialFileMetadata = `-- name: SetSessionInitialFileMetadata :exec
UPDATE sessions SET configuration = jsonb_set(configuration, '{environment,files}', $2::jsonb)
WHERE id = $1
`

type SetSessionInitialFileMetadataParams struct {
	ID      pgtype.UUID `json:"id"`
	Column2 []byte      `json:"column_2"`
}

func (q *Queries) SetSessionInitialFileMetadata(ctx context.Context, arg SetSessionInitialFileMetadataParams) error {
	_, err := q.db.Exec(ctx, setSessionInitialFileMetadata, arg.ID, arg.Column2)
	return err
}
