// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminAuditLog struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	AdminCredentialID string             `json:"admin_credential_id"`
	ActorLabel        string             `json:"actor_label"`
	Action            string             `json:"action"`
	ResourceType      string             `json:"resource_type"`
	ResourceID        string             `json:"resource_id"`
	RequestID         string             `json:"request_id"`
	TraceID           string             `json:"trace_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Agent struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Metadata      []byte             `json:"metadata"`
	Configuration []byte             `json:"configuration"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AgentModelExecution struct {
	AgentID         pgtype.UUID `json:"agent_id"`
	EncryptedConfig []byte      `json:"encrypted_config"`
}

type DeploymentModelProvider struct {
	Harness         string             `json:"harness"`
	Protocol        string             `json:"protocol"`
	BaseUrl         string             `json:"base_url"`
	ContextWindow   int32              `json:"context_window"`
	MaxOutputTokens int32              `json:"max_output_tokens"`
	EncryptedConfig []byte             `json:"encrypted_config"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Revision        pgtype.UUID        `json:"revision"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	LastErrorCode   pgtype.Text        `json:"last_error_code"`
	LastErrorAt     pgtype.Timestamptz `json:"last_error_at"`
	RecoveryPending bool               `json:"recovery_pending"`
	Model           string             `json:"model"`
	HarnessConfig   []byte             `json:"harness_config"`
}

type Device struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	Name                string             `json:"name"`
	CredentialHash      pgtype.Text        `json:"credential_hash"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	LastSeenAt          pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
	EnvironmentID       pgtype.UUID        `json:"environment_id"`
	ExecutorKeyID       pgtype.UUID        `json:"executor_key_id"`
	ArchiveCancelTurnID pgtype.UUID        `json:"archive_cancel_turn_id"`
}

type Environment struct {
	ID             pgtype.UUID        `json:"id"`
	SessionID      pgtype.UUID        `json:"session_id"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	FailureReason  pgtype.Text        `json:"failure_reason"`
	FailedAt       pgtype.Timestamptz `json:"failed_at"`
	FailureDetail  []byte             `json:"failure_detail"`
	Initialization string             `json:"initialization"`
}

type EnvironmentConnection struct {
	EnvironmentID pgtype.UUID `json:"environment_id"`
	Generation    pgtype.UUID `json:"generation"`
	Revision      int64       `json:"revision"`
}

type EnvironmentExecutorCredential struct {
	EnvironmentID pgtype.UUID        `json:"environment_id"`
	TokenSha256   string             `json:"token_sha256"`
	IssuedAt      pgtype.Timestamptz `json:"issued_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	KeyID         pgtype.UUID        `json:"key_id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	SubjectKind   pgtype.Text        `json:"subject_kind"`
	SubjectID     pgtype.Text        `json:"subject_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type EnvironmentFileWrite struct {
	ID            pgtype.UUID        `json:"id"`
	EnvironmentID pgtype.UUID        `json:"environment_id"`
	DeviceID      pgtype.UUID        `json:"device_id"`
	RequestSha256 string             `json:"request_sha256"`
	State         string             `json:"state"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	SettledAt     pgtype.Timestamptz `json:"settled_at"`
	AuditSource   []byte             `json:"audit_source"`
}

type EnvironmentInputReservation struct {
	ID             pgtype.UUID        `json:"id"`
	SessionID      pgtype.UUID        `json:"session_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Batch          []byte             `json:"batch"`
	State          string             `json:"state"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Deadline       pgtype.Timestamptz `json:"deadline"`
	SettledAt      pgtype.Timestamptz `json:"settled_at"`
	IsInitial      bool               `json:"is_initial"`
	FailureCode    pgtype.Text        `json:"failure_code"`
}

type EnvironmentSetup struct {
	SessionID pgtype.UUID `json:"session_id"`
	Contents  []byte      `json:"contents"`
}

type EnvironmentTemplate struct {
	ID                    pgtype.UUID        `json:"id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	Name                  pgtype.Text        `json:"name"`
	NetworkAccess         string             `json:"network_access"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	Files                 []byte             `json:"files"`
	FileContents          []byte             `json:"file_contents"`
	Packages              []byte             `json:"packages"`
	EnvContents           []byte             `json:"env_contents"`
	SetupContents         []byte             `json:"setup_contents"`
	Skills                []byte             `json:"skills"`
	SkillContents         []byte             `json:"skill_contents"`
	NetworkAllowedDomains []string           `json:"network_allowed_domains"`
	Plugins               []byte             `json:"plugins"`
	PluginContents        []byte             `json:"plugin_contents"`
	CapabilityDirectories []string           `json:"capability_directories"`
}

type EnvironmentWorkspace struct {
	ObjectID        pgtype.UUID `json:"object_id"`
	EnvironmentID   pgtype.UUID `json:"environment_id"`
	ConfigurationID pgtype.UUID `json:"configuration_id"`
	State           string      `json:"state"`
	Attachment      []byte      `json:"attachment"`
}

type ExecutionProjectScope struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	OrganizationID string      `json:"organization_id"`
	ProjectID      string      `json:"project_id"`
}

type FunctionCall struct {
	SessionID      pgtype.UUID        `json:"session_id"`
	TurnID         pgtype.UUID        `json:"turn_id"`
	CallID         string             `json:"call_id"`
	ExecutorCallID string             `json:"executor_call_id"`
	Name           string             `json:"name"`
	Arguments      []byte             `json:"arguments"`
	Result         []byte             `json:"result"`
	Applied        bool               `json:"applied"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type InitialEnvironmentFile struct {
	ID        pgtype.UUID `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
	Position  int32       `json:"position"`
	Path      string      `json:"path"`
	SizeBytes int64       `json:"size_bytes"`
	Contents  []byte      `json:"contents"`
}

type NodeHostHistorySample struct {
	NodeID             pgtype.UUID        `json:"node_id"`
	ObservedAt         pgtype.Timestamptz `json:"observed_at"`
	CpuUtilization     pgtype.Float8      `json:"cpu_utilization"`
	MemoryUsedBytes    pgtype.Int8        `json:"memory_used_bytes"`
	AvailableDiskBytes pgtype.Int8        `json:"available_disk_bytes"`
}

type Project struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	SubjectKind string             `json:"subject_kind"`
	SubjectID   string             `json:"subject_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ArchivedAt  pgtype.Timestamptz `json:"archived_at"`
}

type ProjectApiKey struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Prefix      string             `json:"prefix"`
	TokenSha256 string             `json:"token_sha256"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	ProjectID   pgtype.UUID        `json:"project_id"`
}

type PublicExecutionTurn struct {
	ID                     pgtype.UUID        `json:"id"`
	SessionID              pgtype.UUID        `json:"session_id"`
	Status                 string             `json:"status"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	CancelRequestedAt      pgtype.Timestamptz `json:"cancel_requested_at"`
	Outcome                []byte             `json:"outcome"`
	TokenUsage             []byte             `json:"token_usage"`
	ArtifactCaptureStarted bool               `json:"artifact_capture_started"`
	SubagentID             pgtype.UUID        `json:"subagent_id"`
}

type RuntimeAllocation struct {
	ID                    pgtype.UUID        `json:"id"`
	EnvironmentID         pgtype.UUID        `json:"environment_id"`
	DeviceID              pgtype.UUID        `json:"device_id"`
	ProviderKey           pgtype.UUID        `json:"provider_key"`
	State                 string             `json:"state"`
	CreateSettled         bool               `json:"create_settled"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	ReleasedAt            pgtype.Timestamptz `json:"released_at"`
	ComputePhase          string             `json:"compute_phase"`
	ComputeRevision       int64              `json:"compute_revision"`
	ComputeState          []byte             `json:"compute_state"`
	ComputeActivityAt     pgtype.Timestamptz `json:"compute_activity_at"`
	ComputeWakeRequested  bool               `json:"compute_wake_requested"`
	ComputeRetainedUntil  pgtype.Timestamptz `json:"compute_retained_until"`
	NodeID                pgtype.UUID        `json:"node_id"`
	ObservationError      string             `json:"observation_error"`
	ComputePhaseChangedAt pgtype.Timestamptz `json:"compute_phase_changed_at"`
	DeploymentGeneration  pgtype.Int8        `json:"deployment_generation"`
}

type RuntimeDeployment struct {
	Singleton          bool               `json:"singleton"`
	InstallationID     pgtype.UUID        `json:"installation_id"`
	BackendFingerprint string             `json:"backend_fingerprint"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ProviderKind       string             `json:"provider_kind"`
	OwnerEpoch         int64              `json:"owner_epoch"`
	Generation         int64              `json:"generation"`
	Mode               string             `json:"mode"`
	ProviderCredential []byte             `json:"provider_credential"`
	Specification      []byte             `json:"specification"`
	ResetClear         pgtype.Text        `json:"reset_clear"`
	ResetRequestedAt   pgtype.Timestamptz `json:"reset_requested_at"`
	ResetDeadlineAt    pgtype.Timestamptz `json:"reset_deadline_at"`
	ResetForcedAt      pgtype.Timestamptz `json:"reset_forced_at"`
	ResetAudit         []byte             `json:"reset_audit"`
	ProviderConfig     []byte             `json:"provider_config"`
	ProviderMetadata   []byte             `json:"provider_metadata"`
}

type RuntimeDeploymentGeneration struct {
	Generation       int64              `json:"generation"`
	ProviderKind     string             `json:"provider_kind"`
	Specification    []byte             `json:"specification"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ProviderConfig   []byte             `json:"provider_config"`
	ProviderMetadata []byte             `json:"provider_metadata"`
}

type RuntimeDeviceAuthority struct {
	ID             pgtype.UUID `json:"id"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	Name           string      `json:"name"`
	EnvironmentID  pgtype.UUID `json:"environment_id"`
	CredentialHash string      `json:"credential_hash"`
}

type RuntimeHistorySample struct {
	TenantID            pgtype.UUID   `json:"tenant_id"`
	SessionID           pgtype.UUID   `json:"session_id"`
	EnvironmentID       pgtype.UUID   `json:"environment_id"`
	ResolvedAtNs        int64         `json:"resolved_at_ns"`
	AllocationID        pgtype.UUID   `json:"allocation_id"`
	ProviderType        string        `json:"provider_type"`
	Status              string        `json:"status"`
	ObservedAtNs        pgtype.Int8   `json:"observed_at_ns"`
	StartedAtNs         pgtype.Int8   `json:"started_at_ns"`
	CpuUsageSeconds     pgtype.Float8 `json:"cpu_usage_seconds"`
	CpuCapacityCores    pgtype.Float8 `json:"cpu_capacity_cores"`
	MemoryUsageBytes    pgtype.Int8   `json:"memory_usage_bytes"`
	MemoryLimitBytes    pgtype.Int8   `json:"memory_limit_bytes"`
	InputTokens         pgtype.Int8   `json:"input_tokens"`
	OutputTokens        pgtype.Int8   `json:"output_tokens"`
	CpuUtilizationRatio pgtype.Float8 `json:"cpu_utilization_ratio"`
}

type RuntimeNode struct {
	ID                   pgtype.UUID        `json:"id"`
	InstallationID       pgtype.UUID        `json:"installation_id"`
	Name                 string             `json:"name"`
	BackendFingerprint   string             `json:"backend_fingerprint"`
	CredentialSha256     string             `json:"credential_sha256"`
	MaxActive            int32              `json:"max_active"`
	MaxRetained          int32              `json:"max_retained"`
	ConnectionID         pgtype.UUID        `json:"connection_id"`
	ProviderReady        bool               `json:"provider_ready"`
	Health               []byte             `json:"health"`
	ConnectedEpoch       int64              `json:"connected_epoch"`
	LastSeenAt           pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	RemovedAt            pgtype.Timestamptz `json:"removed_at"`
	SpecificationDigest  string             `json:"specification_digest"`
	DeploymentGeneration int64              `json:"deployment_generation"`
	CoreUrl              string             `json:"core_url"`
	EnrollmentID         pgtype.UUID        `json:"enrollment_id"`
	ReadyGeneration      pgtype.Int8        `json:"ready_generation"`
	ProtocolVersion      int32              `json:"protocol_version"`
}

type RuntimeNodeEnrollment struct {
	TokenSha256    string             `json:"token_sha256"`
	InstallationID pgtype.UUID        `json:"installation_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt     pgtype.Timestamptz `json:"consumed_at"`
	NodeID         pgtype.UUID        `json:"node_id"`
	MaxActive      int32              `json:"max_active"`
	MaxRetained    int32              `json:"max_retained"`
	ID             pgtype.UUID        `json:"id"`
}

type RuntimeNodeGenerationStatus struct {
	NodeID              pgtype.UUID        `json:"node_id"`
	Generation          int64              `json:"generation"`
	SpecificationDigest string             `json:"specification_digest"`
	ConnectionID        pgtype.UUID        `json:"connection_id"`
	OwnerEpoch          int64              `json:"owner_epoch"`
	State               string             `json:"state"`
	Diagnostic          string             `json:"diagnostic"`
	ObservedAt          pgtype.Timestamptz `json:"observed_at"`
}

type RuntimePlacement struct {
	EnvironmentID        pgtype.UUID        `json:"environment_id"`
	NodeID               pgtype.UUID        `json:"node_id"`
	ReservedAt           pgtype.Timestamptz `json:"reserved_at"`
	ReleasedAt           pgtype.Timestamptz `json:"released_at"`
	DeploymentGeneration pgtype.Int8        `json:"deployment_generation"`
}

type Session struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	Engine              string             `json:"engine"`
	Metadata            []byte             `json:"metadata"`
	IdempotencyKey      string             `json:"idempotency_key"`
	RequestHash         string             `json:"request_hash"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	Configuration       []byte             `json:"configuration"`
	EventSequence       int64              `json:"event_sequence"`
	CreationRequestHash pgtype.Text        `json:"creation_request_hash"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	CreatorKind         pgtype.Text        `json:"creator_kind"`
	CreatorID           pgtype.Text        `json:"creator_id"`
}

type SessionArtifact struct {
	ID            pgtype.UUID        `json:"id"`
	SessionID     pgtype.UUID        `json:"session_id"`
	TurnID        pgtype.UUID        `json:"turn_id"`
	EnvironmentID pgtype.UUID        `json:"environment_id"`
	Path          string             `json:"path"`
	SizeBytes     int64              `json:"size_bytes"`
	BodyOid       pgtype.Uint32      `json:"body_oid"`
	Sha256        string             `json:"sha256"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type SessionDevice struct {
	SessionID       pgtype.UUID `json:"session_id"`
	DeviceID        pgtype.UUID `json:"device_id"`
	NativeSessionID string      `json:"native_session_id"`
}

type SessionEvent struct {
	SessionID    pgtype.UUID `json:"session_id"`
	Sequence     int64       `json:"sequence"`
	Payload      []byte      `json:"payload"`
	PayloadBytes pgtype.Int4 `json:"payload_bytes"`
}

type SessionExecutionConfiguration struct {
	SessionID                  pgtype.UUID `json:"session_id"`
	Configuration              []byte      `json:"configuration"`
	DeploymentProviderRevision pgtype.UUID `json:"deployment_provider_revision"`
}

type SessionItem struct {
	ID          pgtype.UUID        `json:"id"`
	SessionID   pgtype.UUID        `json:"session_id"`
	TurnID      pgtype.UUID        `json:"turn_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Position    int32              `json:"position"`
	Payload     []byte             `json:"payload"`
	OutputIndex pgtype.Int4        `json:"output_index"`
	SettledAt   pgtype.Timestamptz `json:"settled_at"`
}

type SessionModelExecution struct {
	SessionID       pgtype.UUID `json:"session_id"`
	EncryptedConfig []byte      `json:"encrypted_config"`
}

type Skill struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	DefaultVersion int64              `json:"default_version"`
	LatestVersion  int64              `json:"latest_version"`
	NextVersion    int64              `json:"next_version"`
}

type SkillVersion struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	SkillID     pgtype.UUID        `json:"skill_id"`
	Version     int64              `json:"version"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Contents    []byte             `json:"contents"`
}

type SourceFile struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Filename  string             `json:"filename"`
	Purpose   string             `json:"purpose"`
	BodyOid   pgtype.Uint32      `json:"body_oid"`
	SizeBytes int64              `json:"size_bytes"`
	Sha256    string             `json:"sha256"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SubagentEffect struct {
	SessionID pgtype.UUID `json:"session_id"`
	EffectID  string      `json:"effect_id"`
	Payload   []byte      `json:"payload"`
}

type SubagentIdentity struct {
	ID                pgtype.UUID `json:"id"`
	SessionID         pgtype.UUID `json:"session_id"`
	DeviceID          pgtype.UUID `json:"device_id"`
	Engine            string      `json:"engine"`
	NativeID          string      `json:"native_id"`
	ParentNativeID    string      `json:"parent_native_id"`
	NativeCreatedAt   int64       `json:"native_created_at"`
	FirstTurnID       pgtype.UUID `json:"first_turn_id"`
	FirstEventOrdinal int32       `json:"first_event_ordinal"`
	Name              pgtype.Text `json:"name"`
	Instructions      pgtype.Text `json:"instructions"`
	PublicVisible     bool        `json:"public_visible"`
	Status            string      `json:"status"`
	ClosedAtMs        pgtype.Int8 `json:"closed_at_ms"`
	LifecycleAtMs     int64       `json:"lifecycle_at_ms"`
}

type SubagentItem struct {
	ID          pgtype.UUID `json:"id"`
	SessionID   pgtype.UUID `json:"session_id"`
	SubagentID  pgtype.UUID `json:"subagent_id"`
	TurnID      pgtype.UUID `json:"turn_id"`
	Position    int32       `json:"position"`
	OutputIndex pgtype.Int4 `json:"output_index"`
	Payload     []byte      `json:"payload"`
}

type SubagentTurn struct {
	ID          pgtype.UUID        `json:"id"`
	SessionID   pgtype.UUID        `json:"session_id"`
	SubagentID  pgtype.UUID        `json:"subagent_id"`
	NativeID    string             `json:"native_id"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	TokenUsage  []byte             `json:"token_usage"`
}

type Turn struct {
	ID                     pgtype.UUID        `json:"id"`
	SessionID              pgtype.UUID        `json:"session_id"`
	Status                 string             `json:"status"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	CancelRequestedAt      pgtype.Timestamptz `json:"cancel_requested_at"`
	Outcome                []byte             `json:"outcome"`
	EventCount             int32              `json:"event_count"`
	EventBytes             int64              `json:"event_bytes"`
	TokenUsage             []byte             `json:"token_usage"`
	ArtifactCaptureStarted bool               `json:"artifact_capture_started"`
}

type TurnEvent struct {
	SessionID pgtype.UUID        `json:"session_id"`
	TurnID    pgtype.UUID        `json:"turn_id"`
	Ordinal   int32              `json:"ordinal"`
	Kind      string             `json:"kind"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TurnInput struct {
	Sequence       int64              `json:"sequence"`
	SessionID      pgtype.UUID        `json:"session_id"`
	TurnID         pgtype.UUID        `json:"turn_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Kind           string             `json:"kind"`
	Payload        []byte             `json:"payload"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	BatchPosition  int32              `json:"batch_position"`
}

type Vault struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      pgtype.Text        `json:"name"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Status    string             `json:"status"`
}

type VaultCredential struct {
	ID              pgtype.UUID        `json:"id"`
	VaultID         pgtype.UUID        `json:"vault_id"`
	Name            string             `json:"name"`
	AuthType        string             `json:"auth_type"`
	McpServerUrl    string             `json:"mcp_server_url"`
	TokenCiphertext []byte             `json:"token_ciphertext"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Status          string             `json:"status"`
	OauthMetadata   []byte             `json:"oauth_metadata"`
}

type WorkspaceFsConfiguration struct {
	ID         pgtype.UUID `json:"id"`
	Adapter    string      `json:"adapter"`
	Parameters []byte      `json:"parameters"`
	Active     bool        `json:"active"`
}

type WriteAuditOperation struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	KeyID        string             `json:"key_id"`
	KeyName      string             `json:"key_name"`
	KeyPrefix    string             `json:"key_prefix"`
	KeyKind      string             `json:"key_kind"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   string             `json:"resource_id"`
	ParentID     string             `json:"parent_id"`
	RequestID    string             `json:"request_id"`
	TraceID      string             `json:"trace_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type WriteAuditOwner struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ResourceType string      `json:"resource_type"`
	ResourceID   string      `json:"resource_id"`
	ParentID     string      `json:"parent_id"`
	OperationID  pgtype.UUID `json:"operation_id"`
}
