// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: runtime_lifecycle_nodes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRuntimeLifecyclePlacement = `-- name: GetRuntimeLifecyclePlacement :one
SELECT d.provider_kind, d.mode, a.id AS allocation_id, a.node_id AS allocation_node_id,
       p.node_id AS placement_node_id, p.released_at
FROM environments e JOIN sessions s ON s.id=e.session_id
CROSS JOIN runtime_deployment d
LEFT JOIN runtime_allocations a ON a.environment_id=e.id
LEFT JOIN runtime_placements p ON p.environment_id=e.id
WHERE s.tenant_id=$1 AND e.id=$2
`

type GetRuntimeLifecyclePlacementParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetRuntimeLifecyclePlacementRow struct {
	ProviderKind     string             `json:"provider_kind"`
	Mode             string             `json:"mode"`
	AllocationID     pgtype.UUID        `json:"allocation_id"`
	AllocationNodeID pgtype.UUID        `json:"allocation_node_id"`
	PlacementNodeID  pgtype.UUID        `json:"placement_node_id"`
	ReleasedAt       pgtype.Timestamptz `json:"released_at"`
}

func (q *Queries) GetRuntimeLifecyclePlacement(ctx context.Context, arg GetRuntimeLifecyclePlacementParams) (GetRuntimeLifecyclePlacementRow, error) {
	row := q.db.QueryRow(ctx, getRuntimeLifecyclePlacement, arg.TenantID, arg.ID)
	var i GetRuntimeLifecyclePlacementRow
	err := row.Scan(
		&i.ProviderKind,
		&i.Mode,
		&i.AllocationID,
		&i.AllocationNodeID,
		&i.PlacementNodeID,
		&i.ReleasedAt,
	)
	return i, err
}

const listRuntimeAllocationsForNode = `-- name: ListRuntimeAllocationsForNode :many
SELECT a.id, a.environment_id, a.device_id, a.provider_key, a.state, a.create_settled, a.created_at, a.released_at, a.compute_phase, a.compute_revision, a.compute_state, a.compute_activity_at, a.compute_wake_requested, a.compute_retained_until, a.node_id, a.observation_error, a.compute_phase_changed_at, a.deployment_generation, e.session_id, s.tenant_id, s.deleted_at, (a.compute_phase NOT IN ('disabled', 'running') AND a.compute_retained_until IS NOT NULL AND a.compute_retained_until <= clock_timestamp())::boolean AS expired
FROM runtime_allocations a
JOIN environments e ON e.id=a.environment_id
JOIN sessions s ON s.id=e.session_id
WHERE a.node_id IS NOT DISTINCT FROM $1::uuid
  AND a.id > $2::uuid AND a.state<>'released'
ORDER BY a.id LIMIT 32
`

type ListRuntimeAllocationsForNodeParams struct {
	NodeID  pgtype.UUID `json:"node_id"`
	AfterID pgtype.UUID `json:"after_id"`
}

type ListRuntimeAllocationsForNodeRow struct {
	RuntimeAllocation RuntimeAllocation  `json:"runtime_allocation"`
	SessionID         pgtype.UUID        `json:"session_id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	Expired           bool               `json:"expired"`
}

func (q *Queries) ListRuntimeAllocationsForNode(ctx context.Context, arg ListRuntimeAllocationsForNodeParams) ([]ListRuntimeAllocationsForNodeRow, error) {
	rows, err := q.db.Query(ctx, listRuntimeAllocationsForNode, arg.NodeID, arg.AfterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRuntimeAllocationsForNodeRow{}
	for rows.Next() {
		var i ListRuntimeAllocationsForNodeRow
		if err := rows.Scan(
			&i.RuntimeAllocation.ID,
			&i.RuntimeAllocation.EnvironmentID,
			&i.RuntimeAllocation.DeviceID,
			&i.RuntimeAllocation.ProviderKey,
			&i.RuntimeAllocation.State,
			&i.RuntimeAllocation.CreateSettled,
			&i.RuntimeAllocation.CreatedAt,
			&i.RuntimeAllocation.ReleasedAt,
			&i.RuntimeAllocation.ComputePhase,
			&i.RuntimeAllocation.ComputeRevision,
			&i.RuntimeAllocation.ComputeState,
			&i.RuntimeAllocation.ComputeActivityAt,
			&i.RuntimeAllocation.ComputeWakeRequested,
			&i.RuntimeAllocation.ComputeRetainedUntil,
			&i.RuntimeAllocation.NodeID,
			&i.RuntimeAllocation.ObservationError,
			&i.RuntimeAllocation.ComputePhaseChangedAt,
			&i.RuntimeAllocation.DeploymentGeneration,
			&i.SessionID,
			&i.TenantID,
			&i.DeletedAt,
			&i.Expired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimeLifecycleNodes = `-- name: ListRuntimeLifecycleNodes :many
SELECT n.id FROM runtime_nodes n CROSS JOIN runtime_deployment d
WHERE n.removed_at IS NULL AND n.installation_id=d.installation_id AND d.mode='nodes'
UNION ALL
SELECT NULL::uuid AS id FROM runtime_deployment WHERE mode = 'direct'
ORDER BY id
`

func (q *Queries) ListRuntimeLifecycleNodes(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listRuntimeLifecycleNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnallocatedHostedEnvironmentsForNode = `-- name: ListUnallocatedHostedEnvironmentsForNode :many
SELECT e.id, s.tenant_id
FROM environments e JOIN sessions s ON s.id=e.session_id
LEFT JOIN runtime_placements p ON p.environment_id=e.id
WHERE p.node_id IS NOT DISTINCT FROM $1::uuid
  AND p.released_at IS NULL
  AND (SELECT reset_clear IS NULL FROM runtime_deployment)
  AND e.id > $2::uuid AND s.deleted_at IS NULL AND e.status='pending'
  AND s.configuration->'environment'->>'type'='openai_hosted'
  AND NOT EXISTS (SELECT 1 FROM runtime_allocations a WHERE a.environment_id=e.id)
ORDER BY e.id LIMIT 32
`

type ListUnallocatedHostedEnvironmentsForNodeParams struct {
	NodeID  pgtype.UUID `json:"node_id"`
	AfterID pgtype.UUID `json:"after_id"`
}

type ListUnallocatedHostedEnvironmentsForNodeRow struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ListUnallocatedHostedEnvironmentsForNode(ctx context.Context, arg ListUnallocatedHostedEnvironmentsForNodeParams) ([]ListUnallocatedHostedEnvironmentsForNodeRow, error) {
	rows, err := q.db.Query(ctx, listUnallocatedHostedEnvironmentsForNode, arg.NodeID, arg.AfterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnallocatedHostedEnvironmentsForNodeRow{}
	for rows.Next() {
		var i ListUnallocatedHostedEnvironmentsForNodeRow
		if err := rows.Scan(&i.ID, &i.TenantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
