// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: runtime_allocations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRuntimeAllocation = `-- name: CreateRuntimeAllocation :one
INSERT INTO runtime_allocations (id, environment_id, device_id, provider_key, node_id, deployment_generation, compute_state)
VALUES ($1, $2, $3, $4, $5, $6, jsonb_build_object('protocol_version', $7::text)) RETURNING id, environment_id, device_id, provider_key, state, create_settled, created_at, kept_at, released_at, compute_phase, compute_revision, compute_state, compute_activity_at, compute_wake_requested, compute_retained_until, node_id, observation_error, compute_phase_changed_at, deployment_generation
`

type CreateRuntimeAllocationParams struct {
	ID                   pgtype.UUID `json:"id"`
	EnvironmentID        pgtype.UUID `json:"environment_id"`
	DeviceID             pgtype.UUID `json:"device_id"`
	ProviderKey          pgtype.UUID `json:"provider_key"`
	NodeID               pgtype.UUID `json:"node_id"`
	DeploymentGeneration pgtype.Int8 `json:"deployment_generation"`
	ProtocolVersion      string      `json:"protocol_version"`
}

func (q *Queries) CreateRuntimeAllocation(ctx context.Context, arg CreateRuntimeAllocationParams) (RuntimeAllocation, error) {
	row := q.db.QueryRow(ctx, createRuntimeAllocation,
		arg.ID,
		arg.EnvironmentID,
		arg.DeviceID,
		arg.ProviderKey,
		arg.NodeID,
		arg.DeploymentGeneration,
		arg.ProtocolVersion,
	)
	var i RuntimeAllocation
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.DeviceID,
		&i.ProviderKey,
		&i.State,
		&i.CreateSettled,
		&i.CreatedAt,
		&i.KeptAt,
		&i.ReleasedAt,
		&i.ComputePhase,
		&i.ComputeRevision,
		&i.ComputeState,
		&i.ComputeActivityAt,
		&i.ComputeWakeRequested,
		&i.ComputeRetainedUntil,
		&i.NodeID,
		&i.ObservationError,
		&i.ComputePhaseChangedAt,
		&i.DeploymentGeneration,
	)
	return i, err
}

const getRuntimeAllocation = `-- name: GetRuntimeAllocation :one
SELECT a.id, a.environment_id, a.device_id, a.provider_key, a.state, a.create_settled, a.created_at, a.kept_at, a.released_at, a.compute_phase, a.compute_revision, a.compute_state, a.compute_activity_at, a.compute_wake_requested, a.compute_retained_until, a.node_id, a.observation_error, a.compute_phase_changed_at, a.deployment_generation, e.session_id, s.tenant_id, s.deleted_at, (CASE WHEN a.compute_phase NOT IN ('disabled', 'running') THEN a.compute_retained_until IS NOT NULL AND a.compute_retained_until <= clock_timestamp() ELSE a.node_id IS NULL AND (SELECT mode FROM runtime_deployment) <> 'direct' AND a.kept_at <= clock_timestamp() - interval '1 hour' END)::boolean AS expired
FROM runtime_allocations a
JOIN environments e ON e.id = a.environment_id
JOIN sessions s ON s.id = e.session_id
WHERE s.tenant_id = $1 AND a.environment_id = $2
`

type GetRuntimeAllocationParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
}

type GetRuntimeAllocationRow struct {
	RuntimeAllocation RuntimeAllocation  `json:"runtime_allocation"`
	SessionID         pgtype.UUID        `json:"session_id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	Expired           bool               `json:"expired"`
}

func (q *Queries) GetRuntimeAllocation(ctx context.Context, arg GetRuntimeAllocationParams) (GetRuntimeAllocationRow, error) {
	row := q.db.QueryRow(ctx, getRuntimeAllocation, arg.TenantID, arg.EnvironmentID)
	var i GetRuntimeAllocationRow
	err := row.Scan(
		&i.RuntimeAllocation.ID,
		&i.RuntimeAllocation.EnvironmentID,
		&i.RuntimeAllocation.DeviceID,
		&i.RuntimeAllocation.ProviderKey,
		&i.RuntimeAllocation.State,
		&i.RuntimeAllocation.CreateSettled,
		&i.RuntimeAllocation.CreatedAt,
		&i.RuntimeAllocation.KeptAt,
		&i.RuntimeAllocation.ReleasedAt,
		&i.RuntimeAllocation.ComputePhase,
		&i.RuntimeAllocation.ComputeRevision,
		&i.RuntimeAllocation.ComputeState,
		&i.RuntimeAllocation.ComputeActivityAt,
		&i.RuntimeAllocation.ComputeWakeRequested,
		&i.RuntimeAllocation.ComputeRetainedUntil,
		&i.RuntimeAllocation.NodeID,
		&i.RuntimeAllocation.ObservationError,
		&i.RuntimeAllocation.ComputePhaseChangedAt,
		&i.RuntimeAllocation.DeploymentGeneration,
		&i.SessionID,
		&i.TenantID,
		&i.DeletedAt,
		&i.Expired,
	)
	return i, err
}

const keepRuntimeAllocation = `-- name: KeepRuntimeAllocation :one
UPDATE runtime_allocations SET kept_at = clock_timestamp()
WHERE id = $1 AND state = 'running'
AND (node_id IS NOT NULL OR (SELECT mode FROM runtime_deployment) = 'direct' OR kept_at > clock_timestamp() - interval '1 hour')
RETURNING id, environment_id, device_id, provider_key, state, create_settled, created_at, kept_at, released_at, compute_phase, compute_revision, compute_state, compute_activity_at, compute_wake_requested, compute_retained_until, node_id, observation_error, compute_phase_changed_at, deployment_generation
`

func (q *Queries) KeepRuntimeAllocation(ctx context.Context, id pgtype.UUID) (RuntimeAllocation, error) {
	row := q.db.QueryRow(ctx, keepRuntimeAllocation, id)
	var i RuntimeAllocation
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.DeviceID,
		&i.ProviderKey,
		&i.State,
		&i.CreateSettled,
		&i.CreatedAt,
		&i.KeptAt,
		&i.ReleasedAt,
		&i.ComputePhase,
		&i.ComputeRevision,
		&i.ComputeState,
		&i.ComputeActivityAt,
		&i.ComputeWakeRequested,
		&i.ComputeRetainedUntil,
		&i.NodeID,
		&i.ObservationError,
		&i.ComputePhaseChangedAt,
		&i.DeploymentGeneration,
	)
	return i, err
}

const listRuntimeAllocations = `-- name: ListRuntimeAllocations :many
SELECT a.id, a.environment_id, a.device_id, a.provider_key, a.state, a.create_settled, a.created_at, a.kept_at, a.released_at, a.compute_phase, a.compute_revision, a.compute_state, a.compute_activity_at, a.compute_wake_requested, a.compute_retained_until, a.node_id, a.observation_error, a.compute_phase_changed_at, a.deployment_generation, e.session_id, s.tenant_id, s.deleted_at, (CASE WHEN a.compute_phase NOT IN ('disabled', 'running') THEN a.compute_retained_until IS NOT NULL AND a.compute_retained_until <= clock_timestamp() ELSE a.node_id IS NULL AND (SELECT mode FROM runtime_deployment) <> 'direct' AND a.kept_at <= clock_timestamp() - interval '1 hour' END)::boolean AS expired
FROM runtime_allocations a
JOIN environments e ON e.id = a.environment_id
JOIN sessions s ON s.id = e.session_id
WHERE a.id > $1 AND a.state <> 'released'
ORDER BY a.id LIMIT 32
`

type ListRuntimeAllocationsRow struct {
	RuntimeAllocation RuntimeAllocation  `json:"runtime_allocation"`
	SessionID         pgtype.UUID        `json:"session_id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	Expired           bool               `json:"expired"`
}

func (q *Queries) ListRuntimeAllocations(ctx context.Context, id pgtype.UUID) ([]ListRuntimeAllocationsRow, error) {
	rows, err := q.db.Query(ctx, listRuntimeAllocations, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRuntimeAllocationsRow{}
	for rows.Next() {
		var i ListRuntimeAllocationsRow
		if err := rows.Scan(
			&i.RuntimeAllocation.ID,
			&i.RuntimeAllocation.EnvironmentID,
			&i.RuntimeAllocation.DeviceID,
			&i.RuntimeAllocation.ProviderKey,
			&i.RuntimeAllocation.State,
			&i.RuntimeAllocation.CreateSettled,
			&i.RuntimeAllocation.CreatedAt,
			&i.RuntimeAllocation.KeptAt,
			&i.RuntimeAllocation.ReleasedAt,
			&i.RuntimeAllocation.ComputePhase,
			&i.RuntimeAllocation.ComputeRevision,
			&i.RuntimeAllocation.ComputeState,
			&i.RuntimeAllocation.ComputeActivityAt,
			&i.RuntimeAllocation.ComputeWakeRequested,
			&i.RuntimeAllocation.ComputeRetainedUntil,
			&i.RuntimeAllocation.NodeID,
			&i.RuntimeAllocation.ObservationError,
			&i.RuntimeAllocation.ComputePhaseChangedAt,
			&i.RuntimeAllocation.DeploymentGeneration,
			&i.SessionID,
			&i.TenantID,
			&i.DeletedAt,
			&i.Expired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimeObservationSessions = `-- name: ListRuntimeObservationSessions :many
SELECT s.id, s.tenant_id
FROM sessions s
LEFT JOIN environments e ON e.session_id = s.id
LEFT JOIN runtime_allocations a ON a.environment_id = e.id
WHERE s.id > $1
  AND s.deleted_at IS NULL
  AND s.configuration->'environment'->>'type' = 'openai_hosted'
  AND (a.id IS NULL OR a.state <> 'released')
ORDER BY s.id
LIMIT $2
`

type ListRuntimeObservationSessionsParams struct {
	ID    pgtype.UUID `json:"id"`
	Limit int32       `json:"limit"`
}

type ListRuntimeObservationSessionsRow struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ListRuntimeObservationSessions(ctx context.Context, arg ListRuntimeObservationSessionsParams) ([]ListRuntimeObservationSessionsRow, error) {
	rows, err := q.db.Query(ctx, listRuntimeObservationSessions, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRuntimeObservationSessionsRow{}
	for rows.Next() {
		var i ListRuntimeObservationSessionsRow
		if err := rows.Scan(&i.ID, &i.TenantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const observeRuntimeRunning = `-- name: ObserveRuntimeRunning :one
UPDATE runtime_allocations SET state = 'running', create_settled = true
WHERE id = $1 AND state IN ('creating', 'running')
AND (node_id IS NOT NULL OR (SELECT mode FROM runtime_deployment) = 'direct' OR kept_at > clock_timestamp() - interval '1 hour')
RETURNING id, environment_id, device_id, provider_key, state, create_settled, created_at, kept_at, released_at, compute_phase, compute_revision, compute_state, compute_activity_at, compute_wake_requested, compute_retained_until, node_id, observation_error, compute_phase_changed_at, deployment_generation
`

func (q *Queries) ObserveRuntimeRunning(ctx context.Context, id pgtype.UUID) (RuntimeAllocation, error) {
	row := q.db.QueryRow(ctx, observeRuntimeRunning, id)
	var i RuntimeAllocation
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.DeviceID,
		&i.ProviderKey,
		&i.State,
		&i.CreateSettled,
		&i.CreatedAt,
		&i.KeptAt,
		&i.ReleasedAt,
		&i.ComputePhase,
		&i.ComputeRevision,
		&i.ComputeState,
		&i.ComputeActivityAt,
		&i.ComputeWakeRequested,
		&i.ComputeRetainedUntil,
		&i.NodeID,
		&i.ObservationError,
		&i.ComputePhaseChangedAt,
		&i.DeploymentGeneration,
	)
	return i, err
}

const releaseRuntimeAllocation = `-- name: ReleaseRuntimeAllocation :one
UPDATE runtime_allocations SET state = 'released', released_at = clock_timestamp()
WHERE id = $1 AND state = 'cleanup_pending' AND create_settled RETURNING id, environment_id, device_id, provider_key, state, create_settled, created_at, kept_at, released_at, compute_phase, compute_revision, compute_state, compute_activity_at, compute_wake_requested, compute_retained_until, node_id, observation_error, compute_phase_changed_at, deployment_generation
`

func (q *Queries) ReleaseRuntimeAllocation(ctx context.Context, id pgtype.UUID) (RuntimeAllocation, error) {
	row := q.db.QueryRow(ctx, releaseRuntimeAllocation, id)
	var i RuntimeAllocation
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.DeviceID,
		&i.ProviderKey,
		&i.State,
		&i.CreateSettled,
		&i.CreatedAt,
		&i.KeptAt,
		&i.ReleasedAt,
		&i.ComputePhase,
		&i.ComputeRevision,
		&i.ComputeState,
		&i.ComputeActivityAt,
		&i.ComputeWakeRequested,
		&i.ComputeRetainedUntil,
		&i.NodeID,
		&i.ObservationError,
		&i.ComputePhaseChangedAt,
		&i.DeploymentGeneration,
	)
	return i, err
}

const requestRuntimeCleanup = `-- name: RequestRuntimeCleanup :one
UPDATE runtime_allocations SET state = 'cleanup_pending'
WHERE id = $1 AND state <> 'released' RETURNING id, environment_id, device_id, provider_key, state, create_settled, created_at, kept_at, released_at, compute_phase, compute_revision, compute_state, compute_activity_at, compute_wake_requested, compute_retained_until, node_id, observation_error, compute_phase_changed_at, deployment_generation
`

func (q *Queries) RequestRuntimeCleanup(ctx context.Context, id pgtype.UUID) (RuntimeAllocation, error) {
	row := q.db.QueryRow(ctx, requestRuntimeCleanup, id)
	var i RuntimeAllocation
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.DeviceID,
		&i.ProviderKey,
		&i.State,
		&i.CreateSettled,
		&i.CreatedAt,
		&i.KeptAt,
		&i.ReleasedAt,
		&i.ComputePhase,
		&i.ComputeRevision,
		&i.ComputeState,
		&i.ComputeActivityAt,
		&i.ComputeWakeRequested,
		&i.ComputeRetainedUntil,
		&i.NodeID,
		&i.ObservationError,
		&i.ComputePhaseChangedAt,
		&i.DeploymentGeneration,
	)
	return i, err
}

const settleRuntimeCreation = `-- name: SettleRuntimeCreation :one
UPDATE runtime_allocations SET create_settled = true
WHERE id = $1 AND state <> 'released' RETURNING id, environment_id, device_id, provider_key, state, create_settled, created_at, kept_at, released_at, compute_phase, compute_revision, compute_state, compute_activity_at, compute_wake_requested, compute_retained_until, node_id, observation_error, compute_phase_changed_at, deployment_generation
`

func (q *Queries) SettleRuntimeCreation(ctx context.Context, id pgtype.UUID) (RuntimeAllocation, error) {
	row := q.db.QueryRow(ctx, settleRuntimeCreation, id)
	var i RuntimeAllocation
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.DeviceID,
		&i.ProviderKey,
		&i.State,
		&i.CreateSettled,
		&i.CreatedAt,
		&i.KeptAt,
		&i.ReleasedAt,
		&i.ComputePhase,
		&i.ComputeRevision,
		&i.ComputeState,
		&i.ComputeActivityAt,
		&i.ComputeWakeRequested,
		&i.ComputeRetainedUntil,
		&i.NodeID,
		&i.ObservationError,
		&i.ComputePhaseChangedAt,
		&i.DeploymentGeneration,
	)
	return i, err
}
