// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: runtime_nodes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const connectRuntimeNode = `-- name: ConnectRuntimeNode :execrows
UPDATE runtime_nodes SET connection_id=$2,provider_ready=false,connected_epoch=d.owner_epoch,last_seen_at=clock_timestamp()
FROM runtime_deployment d WHERE runtime_nodes.id=$1 AND removed_at IS NULL AND runtime_nodes.installation_id=d.installation_id AND d.owner_epoch=$3
AND runtime_nodes.connected_epoch <= $3
`

type ConnectRuntimeNodeParams struct {
	ID           pgtype.UUID `json:"id"`
	ConnectionID pgtype.UUID `json:"connection_id"`
	OwnerEpoch   int64       `json:"owner_epoch"`
}

func (q *Queries) ConnectRuntimeNode(ctx context.Context, arg ConnectRuntimeNodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, connectRuntimeNode, arg.ID, arg.ConnectionID, arg.OwnerEpoch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeRuntimeEnrollment = `-- name: ConsumeRuntimeEnrollment :execrows
UPDATE runtime_node_enrollments SET consumed_at=clock_timestamp(),node_id=$2
WHERE token_sha256=$1 AND consumed_at IS NULL AND expires_at>clock_timestamp()
AND installation_id=(SELECT installation_id FROM runtime_deployment WHERE singleton=true)
`

type ConsumeRuntimeEnrollmentParams struct {
	TokenSha256 string      `json:"token_sha256"`
	NodeID      pgtype.UUID `json:"node_id"`
}

func (q *Queries) ConsumeRuntimeEnrollment(ctx context.Context, arg ConsumeRuntimeEnrollmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeRuntimeEnrollment, arg.TokenSha256, arg.NodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createRuntimeEnrollment = `-- name: CreateRuntimeEnrollment :exec
INSERT INTO runtime_node_enrollments(id,token_sha256,installation_id,expires_at,max_active,max_retained) VALUES($1,$2,$3,clock_timestamp()+interval '10 minutes',$4,$5)
`

type CreateRuntimeEnrollmentParams struct {
	ID             pgtype.UUID `json:"id"`
	TokenSha256    string      `json:"token_sha256"`
	InstallationID pgtype.UUID `json:"installation_id"`
	MaxActive      int32       `json:"max_active"`
	MaxRetained    int32       `json:"max_retained"`
}

func (q *Queries) CreateRuntimeEnrollment(ctx context.Context, arg CreateRuntimeEnrollmentParams) error {
	_, err := q.db.Exec(ctx, createRuntimeEnrollment,
		arg.ID,
		arg.TokenSha256,
		arg.InstallationID,
		arg.MaxActive,
		arg.MaxRetained,
	)
	return err
}

const createRuntimePlacement = `-- name: CreateRuntimePlacement :exec
INSERT INTO runtime_placements(environment_id,node_id,deployment_generation) VALUES($1,$2,(SELECT generation FROM runtime_deployment))
`

type CreateRuntimePlacementParams struct {
	EnvironmentID pgtype.UUID `json:"environment_id"`
	NodeID        pgtype.UUID `json:"node_id"`
}

func (q *Queries) CreateRuntimePlacement(ctx context.Context, arg CreateRuntimePlacementParams) error {
	_, err := q.db.Exec(ctx, createRuntimePlacement, arg.EnvironmentID, arg.NodeID)
	return err
}

const createSessionRuntimePlacement = `-- name: CreateSessionRuntimePlacement :exec
INSERT INTO runtime_placements(environment_id,node_id,deployment_generation)
SELECT id,$2,$3::bigint FROM environments WHERE session_id=$1
`

type CreateSessionRuntimePlacementParams struct {
	SessionID  pgtype.UUID `json:"session_id"`
	NodeID     pgtype.UUID `json:"node_id"`
	Generation int64       `json:"generation"`
}

func (q *Queries) CreateSessionRuntimePlacement(ctx context.Context, arg CreateSessionRuntimePlacementParams) error {
	_, err := q.db.Exec(ctx, createSessionRuntimePlacement, arg.SessionID, arg.NodeID, arg.Generation)
	return err
}

const disconnectRuntimeNode = `-- name: DisconnectRuntimeNode :exec
UPDATE runtime_nodes SET connection_id=NULL FROM runtime_deployment d WHERE runtime_nodes.id=$1 AND connection_id=$2 AND connected_epoch=d.owner_epoch AND d.owner_epoch=$3
`

type DisconnectRuntimeNodeParams struct {
	ID           pgtype.UUID `json:"id"`
	ConnectionID pgtype.UUID `json:"connection_id"`
	OwnerEpoch   int64       `json:"owner_epoch"`
}

func (q *Queries) DisconnectRuntimeNode(ctx context.Context, arg DisconnectRuntimeNodeParams) error {
	_, err := q.db.Exec(ctx, disconnectRuntimeNode, arg.ID, arg.ConnectionID, arg.OwnerEpoch)
	return err
}

const getRuntimeDeployment = `-- name: GetRuntimeDeployment :one
SELECT singleton, installation_id, backend_fingerprint, updated_at, provider_kind, owner_epoch, generation, mode, provider_credential, specification, reset_clear, reset_requested_at, reset_deadline_at, reset_forced_at, reset_audit, provider_config, provider_metadata FROM runtime_deployment WHERE singleton=true
`

func (q *Queries) GetRuntimeDeployment(ctx context.Context) (RuntimeDeployment, error) {
	row := q.db.QueryRow(ctx, getRuntimeDeployment)
	var i RuntimeDeployment
	err := row.Scan(
		&i.Singleton,
		&i.InstallationID,
		&i.BackendFingerprint,
		&i.UpdatedAt,
		&i.ProviderKind,
		&i.OwnerEpoch,
		&i.Generation,
		&i.Mode,
		&i.ProviderCredential,
		&i.Specification,
		&i.ResetClear,
		&i.ResetRequestedAt,
		&i.ResetDeadlineAt,
		&i.ResetForcedAt,
		&i.ResetAudit,
		&i.ProviderConfig,
		&i.ProviderMetadata,
	)
	return i, err
}

const getRuntimeEnrollment = `-- name: GetRuntimeEnrollment :one
SELECT token_sha256, installation_id, expires_at, consumed_at, node_id, max_active, max_retained, id FROM runtime_node_enrollments WHERE token_sha256=$1
`

func (q *Queries) GetRuntimeEnrollment(ctx context.Context, tokenSha256 string) (RuntimeNodeEnrollment, error) {
	row := q.db.QueryRow(ctx, getRuntimeEnrollment, tokenSha256)
	var i RuntimeNodeEnrollment
	err := row.Scan(
		&i.TokenSha256,
		&i.InstallationID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.NodeID,
		&i.MaxActive,
		&i.MaxRetained,
		&i.ID,
	)
	return i, err
}

const getRuntimeNode = `-- name: GetRuntimeNode :one
SELECT id, installation_id, name, backend_fingerprint, credential_sha256, max_active, max_retained, connection_id, provider_ready, health, connected_epoch, last_seen_at, created_at, removed_at, specification_digest, deployment_generation, core_url, enrollment_id, ready_generation, protocol_version FROM runtime_nodes WHERE id=$1 AND removed_at IS NULL
`

func (q *Queries) GetRuntimeNode(ctx context.Context, id pgtype.UUID) (RuntimeNode, error) {
	row := q.db.QueryRow(ctx, getRuntimeNode, id)
	var i RuntimeNode
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.Name,
		&i.BackendFingerprint,
		&i.CredentialSha256,
		&i.MaxActive,
		&i.MaxRetained,
		&i.ConnectionID,
		&i.ProviderReady,
		&i.Health,
		&i.ConnectedEpoch,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.RemovedAt,
		&i.SpecificationDigest,
		&i.DeploymentGeneration,
		&i.CoreUrl,
		&i.EnrollmentID,
		&i.ReadyGeneration,
		&i.ProtocolVersion,
	)
	return i, err
}

const getRuntimePlacement = `-- name: GetRuntimePlacement :one
SELECT p.environment_id, p.node_id, p.reserved_at, p.released_at, p.deployment_generation, n.name, (EXISTS(SELECT 1 FROM runtime_node_generation_status g WHERE g.node_id=n.id AND g.generation=p.deployment_generation AND g.connection_id=n.connection_id AND g.owner_epoch=d.owner_epoch AND g.state='ready') AND n.connection_id IS NOT NULL AND n.connected_epoch=d.owner_epoch AND n.last_seen_at>clock_timestamp()-interval '45 seconds' AND n.removed_at IS NULL)::boolean AS available,
 COALESCE(a.observation_error,'')::text AS observation_error, COALESCE(a.state,'reserved')::text AS state, COALESCE(a.compute_phase,'disabled')::text AS compute_phase
FROM runtime_placements p JOIN runtime_nodes n ON n.id=p.node_id CROSS JOIN runtime_deployment d
LEFT JOIN runtime_allocations a ON a.environment_id=p.environment_id WHERE p.environment_id=$1
`

type GetRuntimePlacementRow struct {
	EnvironmentID        pgtype.UUID        `json:"environment_id"`
	NodeID               pgtype.UUID        `json:"node_id"`
	ReservedAt           pgtype.Timestamptz `json:"reserved_at"`
	ReleasedAt           pgtype.Timestamptz `json:"released_at"`
	DeploymentGeneration pgtype.Int8        `json:"deployment_generation"`
	Name                 string             `json:"name"`
	Available            bool               `json:"available"`
	ObservationError     string             `json:"observation_error"`
	State                string             `json:"state"`
	ComputePhase         string             `json:"compute_phase"`
}

func (q *Queries) GetRuntimePlacement(ctx context.Context, environmentID pgtype.UUID) (GetRuntimePlacementRow, error) {
	row := q.db.QueryRow(ctx, getRuntimePlacement, environmentID)
	var i GetRuntimePlacementRow
	err := row.Scan(
		&i.EnvironmentID,
		&i.NodeID,
		&i.ReservedAt,
		&i.ReleasedAt,
		&i.DeploymentGeneration,
		&i.Name,
		&i.Available,
		&i.ObservationError,
		&i.State,
		&i.ComputePhase,
	)
	return i, err
}

const heartbeatRuntimeNode = `-- name: HeartbeatRuntimeNode :execrows
UPDATE runtime_nodes SET last_seen_at=clock_timestamp(),provider_ready=$3,health=$4::jsonb FROM runtime_deployment d
WHERE runtime_nodes.id=$1 AND connection_id=$2 AND removed_at IS NULL AND connected_epoch=d.owner_epoch AND d.owner_epoch=$5
`

type HeartbeatRuntimeNodeParams struct {
	ID            pgtype.UUID `json:"id"`
	ConnectionID  pgtype.UUID `json:"connection_id"`
	ProviderReady bool        `json:"provider_ready"`
	Health        []byte      `json:"health"`
	OwnerEpoch    int64       `json:"owner_epoch"`
}

func (q *Queries) HeartbeatRuntimeNode(ctx context.Context, arg HeartbeatRuntimeNodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatRuntimeNode,
		arg.ID,
		arg.ConnectionID,
		arg.ProviderReady,
		arg.Health,
		arg.OwnerEpoch,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertRuntimeNode = `-- name: InsertRuntimeNode :one
INSERT INTO runtime_nodes(id,installation_id,name,backend_fingerprint,credential_sha256,max_active,max_retained,specification_digest,deployment_generation,core_url,enrollment_id,ready_generation)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$9) RETURNING id, installation_id, name, backend_fingerprint, credential_sha256, max_active, max_retained, connection_id, provider_ready, health, connected_epoch, last_seen_at, created_at, removed_at, specification_digest, deployment_generation, core_url, enrollment_id, ready_generation, protocol_version
`

type InsertRuntimeNodeParams struct {
	ID                   pgtype.UUID `json:"id"`
	InstallationID       pgtype.UUID `json:"installation_id"`
	Name                 string      `json:"name"`
	BackendFingerprint   string      `json:"backend_fingerprint"`
	CredentialSha256     string      `json:"credential_sha256"`
	MaxActive            int32       `json:"max_active"`
	MaxRetained          int32       `json:"max_retained"`
	SpecificationDigest  string      `json:"specification_digest"`
	DeploymentGeneration int64       `json:"deployment_generation"`
	CoreUrl              string      `json:"core_url"`
	EnrollmentID         pgtype.UUID `json:"enrollment_id"`
}

func (q *Queries) InsertRuntimeNode(ctx context.Context, arg InsertRuntimeNodeParams) (RuntimeNode, error) {
	row := q.db.QueryRow(ctx, insertRuntimeNode,
		arg.ID,
		arg.InstallationID,
		arg.Name,
		arg.BackendFingerprint,
		arg.CredentialSha256,
		arg.MaxActive,
		arg.MaxRetained,
		arg.SpecificationDigest,
		arg.DeploymentGeneration,
		arg.CoreUrl,
		arg.EnrollmentID,
	)
	var i RuntimeNode
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.Name,
		&i.BackendFingerprint,
		&i.CredentialSha256,
		&i.MaxActive,
		&i.MaxRetained,
		&i.ConnectionID,
		&i.ProviderReady,
		&i.Health,
		&i.ConnectedEpoch,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.RemovedAt,
		&i.SpecificationDigest,
		&i.DeploymentGeneration,
		&i.CoreUrl,
		&i.EnrollmentID,
		&i.ReadyGeneration,
		&i.ProtocolVersion,
	)
	return i, err
}

const listNodeRuntimeAllocations = `-- name: ListNodeRuntimeAllocations :many
SELECT a.id,a.node_id,a.deployment_generation,a.observation_error,a.state,a.compute_phase,a.compute_phase_changed_at,e.initialization,a.created_at,a.environment_id,e.session_id,s.tenant_id
FROM runtime_allocations a JOIN environments e ON e.id=a.environment_id JOIN sessions s ON s.id=e.session_id
WHERE a.node_id=$1 AND a.state<>'released' ORDER BY a.created_at,a.id LIMIT 1000
`

type ListNodeRuntimeAllocationsRow struct {
	ID                    pgtype.UUID        `json:"id"`
	NodeID                pgtype.UUID        `json:"node_id"`
	DeploymentGeneration  pgtype.Int8        `json:"deployment_generation"`
	ObservationError      string             `json:"observation_error"`
	State                 string             `json:"state"`
	ComputePhase          string             `json:"compute_phase"`
	ComputePhaseChangedAt pgtype.Timestamptz `json:"compute_phase_changed_at"`
	Initialization        string             `json:"initialization"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	EnvironmentID         pgtype.UUID        `json:"environment_id"`
	SessionID             pgtype.UUID        `json:"session_id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
}

func (q *Queries) ListNodeRuntimeAllocations(ctx context.Context, nodeID pgtype.UUID) ([]ListNodeRuntimeAllocationsRow, error) {
	rows, err := q.db.Query(ctx, listNodeRuntimeAllocations, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodeRuntimeAllocationsRow{}
	for rows.Next() {
		var i ListNodeRuntimeAllocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.DeploymentGeneration,
			&i.ObservationError,
			&i.State,
			&i.ComputePhase,
			&i.ComputePhaseChangedAt,
			&i.Initialization,
			&i.CreatedAt,
			&i.EnvironmentID,
			&i.SessionID,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimeNodes = `-- name: ListRuntimeNodes :many
SELECT n.id, n.installation_id, n.name, n.backend_fingerprint, n.credential_sha256, n.max_active, n.max_retained, n.connection_id, n.provider_ready, n.health, n.connected_epoch, n.last_seen_at, n.created_at, n.removed_at, n.specification_digest, n.deployment_generation, n.core_url, n.enrollment_id, n.ready_generation, n.protocol_version, (n.connection_id IS NOT NULL AND n.connected_epoch=d.owner_epoch AND n.last_seen_at > clock_timestamp()-interval '45 seconds')::boolean AS online,
 d.provider_kind, d.generation AS target_generation,
 EXISTS(SELECT 1 FROM runtime_node_generation_status g WHERE g.node_id=n.id AND g.generation=n.ready_generation AND g.connection_id=n.connection_id AND g.owner_epoch=d.owner_epoch AND g.state='ready')::boolean AS serving_ready,
 COALESCE((SELECT g.state FROM runtime_node_generation_status g WHERE g.node_id=n.id AND g.generation=d.generation AND g.connection_id=n.connection_id AND g.owner_epoch=d.owner_epoch),'')::text AS target_state,
 COALESCE((SELECT g.diagnostic FROM runtime_node_generation_status g WHERE g.node_id=n.id AND g.generation=d.generation AND g.connection_id=n.connection_id AND g.owner_epoch=d.owner_epoch),'')::text AS target_diagnostic,
 (SELECT count(*) FROM runtime_placements p LEFT JOIN runtime_allocations a ON a.environment_id=p.environment_id WHERE p.node_id=n.id AND p.released_at IS NULL AND (a.id IS NULL OR a.compute_phase <> 'suspended'))::bigint AS active,
 (SELECT count(*) FROM runtime_placements p WHERE p.node_id=n.id AND p.released_at IS NULL)::bigint AS retained,
 (SELECT count(*) FROM runtime_placements p WHERE p.node_id=n.id AND p.released_at IS NULL AND NOT EXISTS(SELECT 1 FROM runtime_allocations a WHERE a.environment_id=p.environment_id))::bigint AS reserved,
 (SELECT count(*) FROM runtime_allocations a WHERE a.node_id=n.id AND a.state='cleanup_pending')::bigint AS cleanup_pending,
 (SELECT count(*) FROM runtime_allocations a WHERE a.node_id=n.id AND a.state='running' AND a.compute_phase IN('running','disabled'))::bigint AS running,
 (SELECT count(*) FROM runtime_allocations a WHERE a.node_id=n.id AND a.state<>'released' AND a.compute_state->'snapshot' IS NOT NULL AND a.compute_state->'snapshot'<>'null'::jsonb)::bigint AS snapshots
FROM runtime_nodes n CROSS JOIN runtime_deployment d
WHERE n.removed_at IS NULL AND n.installation_id=d.installation_id
AND ($1::uuid IS NULL OR n.id=$1::uuid) ORDER BY n.id
`

type ListRuntimeNodesRow struct {
	ID                   pgtype.UUID        `json:"id"`
	InstallationID       pgtype.UUID        `json:"installation_id"`
	Name                 string             `json:"name"`
	BackendFingerprint   string             `json:"backend_fingerprint"`
	CredentialSha256     string             `json:"credential_sha256"`
	MaxActive            int32              `json:"max_active"`
	MaxRetained          int32              `json:"max_retained"`
	ConnectionID         pgtype.UUID        `json:"connection_id"`
	ProviderReady        bool               `json:"provider_ready"`
	Health               []byte             `json:"health"`
	ConnectedEpoch       int64              `json:"connected_epoch"`
	LastSeenAt           pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	RemovedAt            pgtype.Timestamptz `json:"removed_at"`
	SpecificationDigest  string             `json:"specification_digest"`
	DeploymentGeneration int64              `json:"deployment_generation"`
	CoreUrl              string             `json:"core_url"`
	EnrollmentID         pgtype.UUID        `json:"enrollment_id"`
	ReadyGeneration      pgtype.Int8        `json:"ready_generation"`
	ProtocolVersion      int32              `json:"protocol_version"`
	Online               bool               `json:"online"`
	ProviderKind         string             `json:"provider_kind"`
	TargetGeneration     int64              `json:"target_generation"`
	ServingReady         bool               `json:"serving_ready"`
	TargetState          string             `json:"target_state"`
	TargetDiagnostic     string             `json:"target_diagnostic"`
	Active               int64              `json:"active"`
	Retained             int64              `json:"retained"`
	Reserved             int64              `json:"reserved"`
	CleanupPending       int64              `json:"cleanup_pending"`
	Running              int64              `json:"running"`
	Snapshots            int64              `json:"snapshots"`
}

func (q *Queries) ListRuntimeNodes(ctx context.Context, nodeID pgtype.UUID) ([]ListRuntimeNodesRow, error) {
	rows, err := q.db.Query(ctx, listRuntimeNodes, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRuntimeNodesRow{}
	for rows.Next() {
		var i ListRuntimeNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.Name,
			&i.BackendFingerprint,
			&i.CredentialSha256,
			&i.MaxActive,
			&i.MaxRetained,
			&i.ConnectionID,
			&i.ProviderReady,
			&i.Health,
			&i.ConnectedEpoch,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.RemovedAt,
			&i.SpecificationDigest,
			&i.DeploymentGeneration,
			&i.CoreUrl,
			&i.EnrollmentID,
			&i.ReadyGeneration,
			&i.ProtocolVersion,
			&i.Online,
			&i.ProviderKind,
			&i.TargetGeneration,
			&i.ServingReady,
			&i.TargetState,
			&i.TargetDiagnostic,
			&i.Active,
			&i.Retained,
			&i.Reserved,
			&i.CleanupPending,
			&i.Running,
			&i.Snapshots,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRuntimeNodePresence = `-- name: LockRuntimeNodePresence :one
SELECT id FROM runtime_nodes WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockRuntimeNodePresence(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockRuntimeNodePresence, id)
	err := row.Scan(&id)
	return id, err
}

const releaseRuntimePlacement = `-- name: ReleaseRuntimePlacement :exec
UPDATE runtime_placements SET released_at=COALESCE(released_at,clock_timestamp()) WHERE environment_id=$1
`

func (q *Queries) ReleaseRuntimePlacement(ctx context.Context, environmentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, releaseRuntimePlacement, environmentID)
	return err
}

const releaseUnallocatedRuntimePlacement = `-- name: ReleaseUnallocatedRuntimePlacement :exec
UPDATE runtime_placements SET released_at=COALESCE(released_at,clock_timestamp())
WHERE environment_id IN(SELECT id FROM environments WHERE session_id=$1)
AND NOT EXISTS(SELECT 1 FROM runtime_allocations a WHERE a.environment_id=runtime_placements.environment_id)
`

func (q *Queries) ReleaseUnallocatedRuntimePlacement(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, releaseUnallocatedRuntimePlacement, sessionID)
	return err
}

const removeRuntimeNode = `-- name: RemoveRuntimeNode :exec
UPDATE runtime_nodes SET removed_at=clock_timestamp(),connection_id=NULL,ready_generation=NULL WHERE id=$1 AND removed_at IS NULL
`

func (q *Queries) RemoveRuntimeNode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeRuntimeNode, id)
	return err
}

const setRuntimeObservation = `-- name: SetRuntimeObservation :exec
UPDATE runtime_allocations SET observation_error=$4 WHERE id=$1 AND compute_revision=$2 AND state=$3 AND state<>'released'
`

type SetRuntimeObservationParams struct {
	ID               pgtype.UUID `json:"id"`
	ComputeRevision  int64       `json:"compute_revision"`
	State            string      `json:"state"`
	ObservationError string      `json:"observation_error"`
}

func (q *Queries) SetRuntimeObservation(ctx context.Context, arg SetRuntimeObservationParams) error {
	_, err := q.db.Exec(ctx, setRuntimeObservation,
		arg.ID,
		arg.ComputeRevision,
		arg.State,
		arg.ObservationError,
	)
	return err
}

const updateRuntimeNode = `-- name: UpdateRuntimeNode :one
UPDATE runtime_nodes SET name=$2,max_active=$3,max_retained=$4 WHERE id=$1 AND removed_at IS NULL RETURNING id, installation_id, name, backend_fingerprint, credential_sha256, max_active, max_retained, connection_id, provider_ready, health, connected_epoch, last_seen_at, created_at, removed_at, specification_digest, deployment_generation, core_url, enrollment_id, ready_generation, protocol_version
`

type UpdateRuntimeNodeParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	MaxActive   int32       `json:"max_active"`
	MaxRetained int32       `json:"max_retained"`
}

func (q *Queries) UpdateRuntimeNode(ctx context.Context, arg UpdateRuntimeNodeParams) (RuntimeNode, error) {
	row := q.db.QueryRow(ctx, updateRuntimeNode,
		arg.ID,
		arg.Name,
		arg.MaxActive,
		arg.MaxRetained,
	)
	var i RuntimeNode
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.Name,
		&i.BackendFingerprint,
		&i.CredentialSha256,
		&i.MaxActive,
		&i.MaxRetained,
		&i.ConnectionID,
		&i.ProviderReady,
		&i.Health,
		&i.ConnectedEpoch,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.RemovedAt,
		&i.SpecificationDigest,
		&i.DeploymentGeneration,
		&i.CoreUrl,
		&i.EnrollmentID,
		&i.ReadyGeneration,
		&i.ProtocolVersion,
	)
	return i, err
}
