// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: runtime_suspension.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearRuntimeWake = `-- name: ClearRuntimeWake :exec
UPDATE runtime_allocations
SET compute_wake_requested = false
WHERE id = $1 AND compute_phase = 'running' AND compute_activity_at <= $2
`

type ClearRuntimeWakeParams struct {
	ID                pgtype.UUID        `json:"id"`
	ComputeActivityAt pgtype.Timestamptz `json:"compute_activity_at"`
}

func (q *Queries) ClearRuntimeWake(ctx context.Context, arg ClearRuntimeWakeParams) error {
	_, err := q.db.Exec(ctx, clearRuntimeWake, arg.ID, arg.ComputeActivityAt)
	return err
}

const countRuntimeComputeReservations = `-- name: CountRuntimeComputeReservations :one
SELECT count(*) FROM runtime_allocations
WHERE provider_key = $1 AND state <> 'released' AND compute_phase <> 'suspended'
`

func (q *Queries) CountRuntimeComputeReservations(ctx context.Context, providerKey pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRuntimeComputeReservations, providerKey)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRuntimeRetainedAllocations = `-- name: CountRuntimeRetainedAllocations :one
SELECT count(*) FROM runtime_allocations
WHERE provider_key = $1 AND state <> 'released'
`

func (q *Queries) CountRuntimeRetainedAllocations(ctx context.Context, providerKey pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRuntimeRetainedAllocations, providerKey)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRuntimeActivity = `-- name: GetRuntimeActivity :one
SELECT clock_timestamp()::timestamptz AS observed_at,
    GREATEST(a.compute_activity_at,
    (SELECT max(f.settled_at) FROM environment_file_writes f WHERE f.environment_id = e.id))::timestamptz AS last_activity,
    (EXISTS (SELECT 1 FROM turns t WHERE t.session_id = e.session_id AND t.status IN ('queued','in_progress','waiting'))
     OR EXISTS (SELECT 1 FROM subagent_turns t WHERE t.session_id = e.session_id AND t.status IN ('queued','in_progress','waiting'))
     OR EXISTS (SELECT 1 FROM environment_input_reservations r WHERE r.session_id = e.session_id AND r.state = 'pending')
     OR EXISTS (SELECT 1 FROM environment_file_writes f WHERE f.environment_id = e.id AND f.state = 'pending'))::boolean AS busy,
    a.compute_wake_requested
FROM runtime_allocations a JOIN environments e ON e.id = a.environment_id
WHERE a.id = $1
`

type GetRuntimeActivityRow struct {
	ObservedAt           pgtype.Timestamptz `json:"observed_at"`
	LastActivity         pgtype.Timestamptz `json:"last_activity"`
	Busy                 bool               `json:"busy"`
	ComputeWakeRequested bool               `json:"compute_wake_requested"`
}

func (q *Queries) GetRuntimeActivity(ctx context.Context, id pgtype.UUID) (GetRuntimeActivityRow, error) {
	row := q.db.QueryRow(ctx, getRuntimeActivity, id)
	var i GetRuntimeActivityRow
	err := row.Scan(
		&i.ObservedAt,
		&i.LastActivity,
		&i.Busy,
		&i.ComputeWakeRequested,
	)
	return i, err
}

const hasIncompatibleRuntimeComputeState = `-- name: HasIncompatibleRuntimeComputeState :one
SELECT EXISTS (
 SELECT 1 FROM runtime_allocations
 WHERE state <> 'released'
 AND (compute_state->>'protocol_version') IS DISTINCT FROM $1::text
)::boolean
`

func (q *Queries) HasIncompatibleRuntimeComputeState(ctx context.Context, protocolVersion string) (bool, error) {
	row := q.db.QueryRow(ctx, hasIncompatibleRuntimeComputeState, protocolVersion)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const recordRuntimeTerminalActivity = `-- name: RecordRuntimeTerminalActivity :exec
UPDATE runtime_allocations a SET compute_activity_at = clock_timestamp()
FROM environments e
WHERE a.environment_id = e.id AND e.session_id = $1
    AND a.state = 'running'
`

func (q *Queries) RecordRuntimeTerminalActivity(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, recordRuntimeTerminalActivity, sessionID)
	return err
}

const runtimeComputeBlocksAdmission = `-- name: RuntimeComputeBlocksAdmission :one
SELECT EXISTS (
    SELECT 1 FROM runtime_allocations a JOIN environments e ON e.id = a.environment_id
    WHERE e.session_id = $1 AND a.compute_phase NOT IN ('disabled', 'running')
)::boolean
`

func (q *Queries) RuntimeComputeBlocksAdmission(ctx context.Context, sessionID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, runtimeComputeBlocksAdmission, sessionID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const sessionHasRuntimeNode = `-- name: SessionHasRuntimeNode :one
SELECT EXISTS (
    SELECT 1 FROM runtime_allocations a JOIN environments e ON e.id = a.environment_id
    WHERE e.session_id = $1 AND a.node_id IS NOT NULL
)::boolean
`

func (q *Queries) SessionHasRuntimeNode(ctx context.Context, sessionID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, sessionHasRuntimeNode, sessionID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const setRuntimeCompute = `-- name: SetRuntimeCompute :one
UPDATE runtime_allocations
SET compute_phase_changed_at = CASE WHEN compute_phase = $1::text THEN compute_phase_changed_at ELSE clock_timestamp() END,
    compute_phase = $1, compute_state = $2::jsonb,
    compute_revision = compute_revision + 1,
    compute_retained_until = $3,
    kept_at = CASE WHEN $1::text = 'running' THEN clock_timestamp() ELSE kept_at END
WHERE runtime_allocations.id = $4 AND compute_revision = $5
    AND state = 'running' AND EXISTS (SELECT 1 FROM environments e WHERE e.id = runtime_allocations.environment_id AND e.initialization = 'complete')
    AND ((compute_phase IN ('disabled','running') AND (node_id IS NOT NULL OR (SELECT mode FROM runtime_deployment) = 'direct' OR kept_at > clock_timestamp() - interval '1 hour'))
      OR (compute_phase NOT IN ('disabled','running') AND compute_retained_until > clock_timestamp()))
RETURNING id, environment_id, device_id, provider_key, state, create_settled, created_at, kept_at, released_at, compute_phase, compute_revision, compute_state, compute_activity_at, compute_wake_requested, compute_retained_until, node_id, observation_error, compute_phase_changed_at, deployment_generation
`

type SetRuntimeComputeParams struct {
	Phase         string             `json:"phase"`
	State         []byte             `json:"state"`
	RetainedUntil pgtype.Timestamptz `json:"retained_until"`
	ID            pgtype.UUID        `json:"id"`
	Revision      int64              `json:"revision"`
}

func (q *Queries) SetRuntimeCompute(ctx context.Context, arg SetRuntimeComputeParams) (RuntimeAllocation, error) {
	row := q.db.QueryRow(ctx, setRuntimeCompute,
		arg.Phase,
		arg.State,
		arg.RetainedUntil,
		arg.ID,
		arg.Revision,
	)
	var i RuntimeAllocation
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.DeviceID,
		&i.ProviderKey,
		&i.State,
		&i.CreateSettled,
		&i.CreatedAt,
		&i.KeptAt,
		&i.ReleasedAt,
		&i.ComputePhase,
		&i.ComputeRevision,
		&i.ComputeState,
		&i.ComputeActivityAt,
		&i.ComputeWakeRequested,
		&i.ComputeRetainedUntil,
		&i.NodeID,
		&i.ObservationError,
		&i.ComputePhaseChangedAt,
		&i.DeploymentGeneration,
	)
	return i, err
}

const touchRuntimeActivity = `-- name: TouchRuntimeActivity :exec
UPDATE runtime_allocations a
SET compute_activity_at = clock_timestamp(), compute_wake_requested = true
FROM environments e JOIN sessions s ON s.id = e.session_id
WHERE a.environment_id = e.id AND s.tenant_id = $1
    AND e.id = $2 AND s.deleted_at IS NULL
    AND a.state = 'running' AND a.compute_phase <> 'disabled'
`

type TouchRuntimeActivityParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
}

func (q *Queries) TouchRuntimeActivity(ctx context.Context, arg TouchRuntimeActivityParams) error {
	_, err := q.db.Exec(ctx, touchRuntimeActivity, arg.TenantID, arg.EnvironmentID)
	return err
}
