// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: runtime_deployment.sql

package sqlc

import (
	"context"
)

const countAddressBindings = `-- name: CountAddressBindings :one
SELECT
(SELECT count(*) FROM runtime_nodes WHERE removed_at IS NULL)::bigint AS nodes,
(SELECT count(*) FROM runtime_nodes WHERE removed_at IS NULL AND core_url <> $1::text)::bigint AS nodes_on_other_address,
(SELECT count(*) FROM environment_executor_credentials c
 LEFT JOIN environments e ON e.id = c.environment_id LEFT JOIN sessions s ON s.id = e.session_id
 WHERE c.revoked_at IS NULL AND (c.environment_id IS NULL OR s.deleted_at IS NULL))::bigint AS self_hosted_executors
`

type CountAddressBindingsRow struct {
	Nodes               int64 `json:"nodes"`
	NodesOnOtherAddress int64 `json:"nodes_on_other_address"`
	SelfHostedExecutors int64 `json:"self_hosted_executors"`
}

func (q *Queries) CountAddressBindings(ctx context.Context, publicUrl string) (CountAddressBindingsRow, error) {
	row := q.db.QueryRow(ctx, countAddressBindings, publicUrl)
	var i CountAddressBindingsRow
	err := row.Scan(&i.Nodes, &i.NodesOnOtherAddress, &i.SelfHostedExecutors)
	return i, err
}

const countRuntimeDeploymentResources = `-- name: CountRuntimeDeploymentResources :one
SELECT
(SELECT count(*) FROM runtime_allocations WHERE state <> 'released')::bigint AS allocations,
(SELECT count(*) FROM environments e JOIN sessions s ON s.id = e.session_id
 WHERE s.deleted_at IS NULL AND e.status = 'pending'
 AND s.configuration->'environment'->>'type' = 'openai_hosted'
 AND NOT EXISTS (SELECT 1 FROM runtime_allocations a WHERE a.environment_id = e.id))::bigint AS pending
`

type CountRuntimeDeploymentResourcesRow struct {
	Allocations int64 `json:"allocations"`
	Pending     int64 `json:"pending"`
}

func (q *Queries) CountRuntimeDeploymentResources(ctx context.Context) (CountRuntimeDeploymentResourcesRow, error) {
	row := q.db.QueryRow(ctx, countRuntimeDeploymentResources)
	var i CountRuntimeDeploymentResourcesRow
	err := row.Scan(&i.Allocations, &i.Pending)
	return i, err
}

const lockRuntimeDeployment = `-- name: LockRuntimeDeployment :one
SELECT singleton, installation_id, backend_fingerprint, updated_at, provider_kind, owner_epoch, generation, mode, provider_credential, specification, reset_clear, reset_requested_at, reset_deadline_at, reset_forced_at, reset_audit, provider_config, provider_metadata FROM runtime_deployment WHERE singleton = true FOR UPDATE
`

func (q *Queries) LockRuntimeDeployment(ctx context.Context) (RuntimeDeployment, error) {
	row := q.db.QueryRow(ctx, lockRuntimeDeployment)
	var i RuntimeDeployment
	err := row.Scan(
		&i.Singleton,
		&i.InstallationID,
		&i.BackendFingerprint,
		&i.UpdatedAt,
		&i.ProviderKind,
		&i.OwnerEpoch,
		&i.Generation,
		&i.Mode,
		&i.ProviderCredential,
		&i.Specification,
		&i.ResetClear,
		&i.ResetRequestedAt,
		&i.ResetDeadlineAt,
		&i.ResetForcedAt,
		&i.ResetAudit,
		&i.ProviderConfig,
		&i.ProviderMetadata,
	)
	return i, err
}
