// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sandbox_reset.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSandboxReset = `-- name: CancelSandboxReset :exec
UPDATE runtime_deployment SET admission_paused = false, reset_clear = NULL,
    reset_requested_at = NULL, reset_deadline_at = NULL, reset_forced_at = NULL,
    reset_audit = NULL, updated_at = clock_timestamp()
WHERE singleton = true
`

func (q *Queries) CancelSandboxReset(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cancelSandboxReset)
	return err
}

const completeSandboxReset = `-- name: CompleteSandboxReset :exec
UPDATE runtime_deployment SET provider_kind = '', backend_fingerprint = '', mode = '',
    specification = '{}', idle_seconds = 0, retention_seconds = 0,
    provider_config = '{}'::jsonb, provider_metadata = '{}'::jsonb, provider_credential = NULL,
    generation = generation + 1, owner_epoch = owner_epoch + 1,
    admission_paused = false, reset_clear = NULL, reset_requested_at = NULL,
    reset_deadline_at = NULL, reset_forced_at = NULL, reset_audit = NULL,
    updated_at = clock_timestamp()
WHERE singleton = true
`

func (q *Queries) CompleteSandboxReset(ctx context.Context) error {
	_, err := q.db.Exec(ctx, completeSandboxReset)
	return err
}

const forceSandboxReset = `-- name: ForceSandboxReset :exec
WITH clock AS MATERIALIZED (SELECT clock_timestamp() AS at)
UPDATE runtime_deployment SET reset_clear = 'force', reset_forced_at = clock.at, updated_at = clock.at
FROM clock WHERE singleton = true AND reset_clear = 'auto'
`

func (q *Queries) ForceSandboxReset(ctx context.Context) error {
	_, err := q.db.Exec(ctx, forceSandboxReset)
	return err
}

const getSandboxDeploymentSnapshot = `-- name: GetSandboxDeploymentSnapshot :one
WITH deployment AS MATERIALIZED (SELECT singleton, installation_id, backend_fingerprint, admission_paused, updated_at, provider_kind, local_node_id, owner_epoch, web_managed, idle_seconds, retention_seconds, generation, mode, provider_credential, specification, reset_clear, reset_requested_at, reset_deadline_at, reset_forced_at, reset_audit, provider_config, provider_metadata FROM runtime_deployment WHERE singleton = true LIMIT 1),
observed AS MATERIALIZED (SELECT clock_timestamp() AS as_of),
held AS (
    SELECT a.deployment_generation, a.node_id, s.id AS session_id, e.id AS environment_id, false AS pending,
        (a.state = 'cleanup_pending' OR s.deleted_at IS NOT NULL OR e.status IN ('failed', 'expired')
         OR CASE WHEN a.compute_phase NOT IN ('disabled', 'running')
            THEN a.compute_retained_until IS NOT NULL AND a.compute_retained_until <= observed.as_of
            ELSE a.node_id IS NULL AND d.mode <> 'direct' AND a.kept_at <= observed.as_of - interval '1 hour' END) AS cleanup
    FROM runtime_allocations a JOIN environments e ON e.id = a.environment_id
    JOIN sessions s ON s.id = e.session_id CROSS JOIN deployment d CROSS JOIN observed
    WHERE a.state <> 'released'
    UNION ALL
    SELECT p.deployment_generation, p.node_id, s.id, e.id, true, false
    FROM environments e JOIN sessions s ON s.id = e.session_id
    LEFT JOIN runtime_placements p ON p.environment_id = e.id AND p.released_at IS NULL
    WHERE s.deleted_at IS NULL AND e.status = 'pending'
        AND s.configuration->'environment'->>'type' = 'openai_hosted'
        AND NOT EXISTS (SELECT 1 FROM runtime_allocations a WHERE a.environment_id = e.id)
), classified AS (
    SELECT h.deployment_generation, h.node_id, h.session_id, h.environment_id, h.pending, h.cleanup, CASE WHEN h.cleanup THEN 'cleanup'
        WHEN EXISTS (SELECT 1 FROM turns t WHERE t.session_id = h.session_id AND t.status IN ('in_progress', 'waiting'))
          OR EXISTS (SELECT 1 FROM subagent_turns t WHERE t.session_id = h.session_id AND t.status IN ('in_progress', 'waiting'))
          OR EXISTS (SELECT 1 FROM environment_file_writes f WHERE f.environment_id = h.environment_id AND f.state = 'pending')
        THEN 'busy' ELSE 'idle' END AS category,
        n.name, (h.node_id IS NOT NULL AND NOT COALESCE(n.removed_at IS NULL AND n.connection_id IS NOT NULL
            AND n.connected_epoch = d.owner_epoch AND n.last_seen_at > observed.as_of - interval '45 seconds', false)) AS offline
    FROM held h LEFT JOIN runtime_nodes n ON n.id = h.node_id CROSS JOIN deployment d CROSS JOIN observed
), rollout_nodes AS (
    SELECT CASE
        WHEN n.connection_id IS NULL OR n.connected_epoch <> d.owner_epoch OR n.last_seen_at IS NULL OR n.last_seen_at <= observed.as_of - interval '45 seconds' THEN 'unknown'
        WHEN n.protocol_version=1 AND n.deployment_generation <> d.generation THEN 'update_required'
        ELSE COALESCE(g.state,'unknown') END AS state
    FROM runtime_nodes n CROSS JOIN deployment d CROSS JOIN observed
    LEFT JOIN runtime_node_generation_status g ON g.node_id=n.id AND g.generation=d.generation AND g.connection_id=n.connection_id AND g.owner_epoch=d.owner_epoch
    WHERE n.removed_at IS NULL AND n.installation_id=d.installation_id
), offline AS (
    SELECT node_id, name, count(*)::bigint AS resources FROM classified WHERE offline GROUP BY node_id, name
)
SELECT d.singleton, d.installation_id, d.backend_fingerprint, d.admission_paused, d.updated_at, d.provider_kind, d.local_node_id, d.owner_epoch, d.web_managed, d.idle_seconds, d.retention_seconds, d.generation, d.mode, d.provider_credential, d.specification, d.reset_clear, d.reset_requested_at, d.reset_deadline_at, d.reset_forced_at, d.reset_audit, d.provider_config, d.provider_metadata,
    (SELECT count(*) FROM classified WHERE NOT pending)::bigint AS allocations,
    (SELECT count(*) FROM classified WHERE pending)::bigint AS pending,
    jsonb_build_object(
        'busy', (SELECT count(*) FROM classified WHERE category = 'busy'),
        'idle', (SELECT count(*) FROM classified WHERE category = 'idle'),
        'cleanup', (SELECT count(*) FROM classified WHERE category = 'cleanup'),
        'on_offline_nodes', (SELECT count(*) FROM classified WHERE offline),
        'offline_nodes', COALESCE((SELECT jsonb_agg(jsonb_build_object('node_id', node_id, 'name', name, 'resources', resources) ORDER BY node_id) FROM offline), '[]'::jsonb)
    )::jsonb AS remaining,
    jsonb_build_object('state',CASE WHEN EXISTS(SELECT 1 FROM rollout_nodes WHERE state='preparing') THEN 'preparing' ELSE 'settled' END,
        'previous_generation_sandboxes',(SELECT count(*) FROM held h WHERE h.deployment_generation <> d.generation),
        'nodes',CASE WHEN d.mode='nodes' THEN jsonb_build_object(
            'ready',(SELECT count(*) FROM rollout_nodes WHERE state='ready'),
            'preparing',(SELECT count(*) FROM rollout_nodes WHERE state='preparing'),
            'failed',(SELECT count(*) FROM rollout_nodes WHERE state='failed'),
            'update_required',(SELECT count(*) FROM rollout_nodes WHERE state='update_required'),
            'unknown',(SELECT count(*) FROM rollout_nodes WHERE state='unknown')) ELSE NULL END
    )::jsonb AS rollout
FROM runtime_deployment d
WHERE d.singleton = true
LIMIT 1
`

type GetSandboxDeploymentSnapshotRow struct {
	RuntimeDeployment RuntimeDeployment `json:"runtime_deployment"`
	Allocations       int64             `json:"allocations"`
	Pending           int64             `json:"pending"`
	Remaining         []byte            `json:"remaining"`
	Rollout           []byte            `json:"rollout"`
}

func (q *Queries) GetSandboxDeploymentSnapshot(ctx context.Context) (GetSandboxDeploymentSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getSandboxDeploymentSnapshot)
	var i GetSandboxDeploymentSnapshotRow
	err := row.Scan(
		&i.RuntimeDeployment.Singleton,
		&i.RuntimeDeployment.InstallationID,
		&i.RuntimeDeployment.BackendFingerprint,
		&i.RuntimeDeployment.AdmissionPaused,
		&i.RuntimeDeployment.UpdatedAt,
		&i.RuntimeDeployment.ProviderKind,
		&i.RuntimeDeployment.LocalNodeID,
		&i.RuntimeDeployment.OwnerEpoch,
		&i.RuntimeDeployment.WebManaged,
		&i.RuntimeDeployment.IdleSeconds,
		&i.RuntimeDeployment.RetentionSeconds,
		&i.RuntimeDeployment.Generation,
		&i.RuntimeDeployment.Mode,
		&i.RuntimeDeployment.ProviderCredential,
		&i.RuntimeDeployment.Specification,
		&i.RuntimeDeployment.ResetClear,
		&i.RuntimeDeployment.ResetRequestedAt,
		&i.RuntimeDeployment.ResetDeadlineAt,
		&i.RuntimeDeployment.ResetForcedAt,
		&i.RuntimeDeployment.ResetAudit,
		&i.RuntimeDeployment.ProviderConfig,
		&i.RuntimeDeployment.ProviderMetadata,
		&i.Allocations,
		&i.Pending,
		&i.Remaining,
		&i.Rollout,
	)
	return i, err
}

const getSandboxResetProject = `-- name: GetSandboxResetProject :one
SELECT id FROM projects WHERE tenant_id = $1
`

func (q *Queries) GetSandboxResetProject(ctx context.Context, tenantID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getSandboxResetProject, tenantID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listSandboxResetSessions = `-- name: ListSandboxResetSessions :many
SELECT s.id, s.tenant_id
FROM sessions s JOIN environments e ON e.session_id = s.id
WHERE s.deleted_at IS NULL AND s.configuration->'environment'->>'type' = 'openai_hosted'
    AND e.status NOT IN ('failed', 'expired')
    AND s.id > $1::uuid
    AND (EXISTS (SELECT 1 FROM runtime_allocations a WHERE a.environment_id = e.id AND a.state NOT IN ('released', 'cleanup_pending'))
        OR (e.status = 'pending' AND NOT EXISTS (SELECT 1 FROM runtime_allocations a WHERE a.environment_id = e.id)))
    AND ($2::boolean OR NOT (
        EXISTS (SELECT 1 FROM turns t WHERE t.session_id = s.id AND t.status IN ('in_progress', 'waiting'))
        OR EXISTS (SELECT 1 FROM subagent_turns t WHERE t.session_id = s.id AND t.status IN ('in_progress', 'waiting'))
        OR EXISTS (SELECT 1 FROM environment_file_writes f WHERE f.environment_id = e.id AND f.state = 'pending')
    ))
ORDER BY s.id LIMIT 32
`

type ListSandboxResetSessionsParams struct {
	AfterID pgtype.UUID `json:"after_id"`
	Force   bool        `json:"force"`
}

type ListSandboxResetSessionsRow struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ListSandboxResetSessions(ctx context.Context, arg ListSandboxResetSessionsParams) ([]ListSandboxResetSessionsRow, error) {
	rows, err := q.db.Query(ctx, listSandboxResetSessions, arg.AfterID, arg.Force)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSandboxResetSessionsRow{}
	for rows.Next() {
		var i ListSandboxResetSessionsRow
		if err := rows.Scan(&i.ID, &i.TenantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionBlocksAutoReset = `-- name: SessionBlocksAutoReset :one
SELECT (
    EXISTS (SELECT 1 FROM turns t WHERE t.session_id = $1 AND status IN ('in_progress', 'waiting'))
    OR EXISTS (SELECT 1 FROM subagent_turns t WHERE t.session_id = $1 AND status IN ('in_progress', 'waiting'))
    OR EXISTS (SELECT 1 FROM environment_file_writes f JOIN environments e ON e.id = f.environment_id
        WHERE e.session_id = $1 AND f.state = 'pending')
)::boolean
`

func (q *Queries) SessionBlocksAutoReset(ctx context.Context, sessionID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, sessionBlocksAutoReset, sessionID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const startSandboxReset = `-- name: StartSandboxReset :exec
WITH clock AS MATERIALIZED (SELECT clock_timestamp() AS at)
UPDATE runtime_deployment SET admission_paused = true, reset_clear = $1,
    reset_requested_at = clock.at,
    reset_deadline_at = CASE WHEN $1::text = 'auto'
        THEN clock.at + make_interval(secs => $2::int) END,
    reset_forced_at = CASE WHEN $1::text = 'force' THEN clock.at END,
    reset_audit = $3::jsonb, updated_at = clock.at
FROM clock WHERE singleton = true
`

type StartSandboxResetParams struct {
	Clear           pgtype.Text `json:"clear"`
	DeadlineSeconds int32       `json:"deadline_seconds"`
	Audit           []byte      `json:"audit"`
}

func (q *Queries) StartSandboxReset(ctx context.Context, arg StartSandboxResetParams) error {
	_, err := q.db.Exec(ctx, startSandboxReset, arg.Clear, arg.DeadlineSeconds, arg.Audit)
	return err
}
