// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sandbox_deployment_setup.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceSandboxOwnerEpoch = `-- name: AdvanceSandboxOwnerEpoch :exec
UPDATE runtime_deployment SET owner_epoch=owner_epoch+1 WHERE singleton=true
`

func (q *Queries) AdvanceSandboxOwnerEpoch(ctx context.Context) error {
	_, err := q.db.Exec(ctx, advanceSandboxOwnerEpoch)
	return err
}

const claimWebSandboxDeployment = `-- name: ClaimWebSandboxDeployment :exec
UPDATE runtime_deployment SET installation_id=$1,
owner_epoch=owner_epoch+1, updated_at=clock_timestamp() WHERE singleton=true
`

func (q *Queries) ClaimWebSandboxDeployment(ctx context.Context, installationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, claimWebSandboxDeployment, installationID)
	return err
}

const initializeSandboxDeployment = `-- name: InitializeSandboxDeployment :exec
UPDATE runtime_deployment SET provider_kind=$1, backend_fingerprint=$2,
generation=$3, mode=$4,
provider_config=$5,provider_metadata=$6,provider_credential=$7,specification=$8,
updated_at=clock_timestamp() WHERE singleton=true
`

type InitializeSandboxDeploymentParams struct {
	ProviderKind       string `json:"provider_kind"`
	BackendFingerprint string `json:"backend_fingerprint"`
	Generation         int64  `json:"generation"`
	Mode               string `json:"mode"`
	ProviderConfig     []byte `json:"provider_config"`
	ProviderMetadata   []byte `json:"provider_metadata"`
	ProviderCredential []byte `json:"provider_credential"`
	Specification      []byte `json:"specification"`
}

func (q *Queries) InitializeSandboxDeployment(ctx context.Context, arg InitializeSandboxDeploymentParams) error {
	_, err := q.db.Exec(ctx, initializeSandboxDeployment,
		arg.ProviderKind,
		arg.BackendFingerprint,
		arg.Generation,
		arg.Mode,
		arg.ProviderConfig,
		arg.ProviderMetadata,
		arg.ProviderCredential,
		arg.Specification,
	)
	return err
}

const recordSandboxConfigurationMetadata = `-- name: RecordSandboxConfigurationMetadata :exec
UPDATE runtime_deployment SET provider_metadata=$1,updated_at=clock_timestamp()
WHERE singleton=true AND provider_kind<>''
`

func (q *Queries) RecordSandboxConfigurationMetadata(ctx context.Context, providerMetadata []byte) error {
	_, err := q.db.Exec(ctx, recordSandboxConfigurationMetadata, providerMetadata)
	return err
}

const retireSandboxEnrollments = `-- name: RetireSandboxEnrollments :exec
UPDATE runtime_node_enrollments SET expires_at=clock_timestamp() WHERE consumed_at IS NULL
`

func (q *Queries) RetireSandboxEnrollments(ctx context.Context) error {
	_, err := q.db.Exec(ctx, retireSandboxEnrollments)
	return err
}

const retireSandboxNodes = `-- name: RetireSandboxNodes :exec
UPDATE runtime_nodes SET removed_at=clock_timestamp(),connection_id=NULL,provider_ready=false,ready_generation=NULL WHERE removed_at IS NULL
`

func (q *Queries) RetireSandboxNodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, retireSandboxNodes)
	return err
}
