// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: source_files.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSourceFile = `-- name: CreateSourceFile :one
INSERT INTO source_files (id, tenant_id, filename, purpose, body_oid, size_bytes, sha256)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, filename, purpose, body_oid, size_bytes, sha256, created_at
`

type CreateSourceFileParams struct {
	ID        pgtype.UUID   `json:"id"`
	TenantID  pgtype.UUID   `json:"tenant_id"`
	Filename  string        `json:"filename"`
	Purpose   string        `json:"purpose"`
	BodyOid   pgtype.Uint32 `json:"body_oid"`
	SizeBytes int64         `json:"size_bytes"`
	Sha256    string        `json:"sha256"`
}

func (q *Queries) CreateSourceFile(ctx context.Context, arg CreateSourceFileParams) (SourceFile, error) {
	row := q.db.QueryRow(ctx, createSourceFile,
		arg.ID,
		arg.TenantID,
		arg.Filename,
		arg.Purpose,
		arg.BodyOid,
		arg.SizeBytes,
		arg.Sha256,
	)
	var i SourceFile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Filename,
		&i.Purpose,
		&i.BodyOid,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSourceFile = `-- name: DeleteSourceFile :one
DELETE FROM source_files WHERE tenant_id = $1 AND id = $2 RETURNING body_oid
`

type DeleteSourceFileParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteSourceFile(ctx context.Context, arg DeleteSourceFileParams) (pgtype.Uint32, error) {
	row := q.db.QueryRow(ctx, deleteSourceFile, arg.TenantID, arg.ID)
	var body_oid pgtype.Uint32
	err := row.Scan(&body_oid)
	return body_oid, err
}

const getSourceFile = `-- name: GetSourceFile :one
SELECT id, tenant_id, filename, purpose, body_oid, size_bytes, sha256, created_at FROM source_files WHERE tenant_id = $1 AND id = $2
`

type GetSourceFileParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetSourceFile(ctx context.Context, arg GetSourceFileParams) (SourceFile, error) {
	row := q.db.QueryRow(ctx, getSourceFile, arg.TenantID, arg.ID)
	var i SourceFile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Filename,
		&i.Purpose,
		&i.BodyOid,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const listSourceFiles = `-- name: ListSourceFiles :many
SELECT id, tenant_id, filename, purpose, body_oid, size_bytes, sha256, created_at FROM source_files
WHERE tenant_id = $1
  AND ($2::text IS NULL OR purpose = $2::text)
  AND ($3::timestamptz IS NULL
    OR (NOT $4::boolean AND (created_at, id) < ($3::timestamptz, $5::uuid))
    OR ($4::boolean AND (created_at, id) > ($3::timestamptz, $5::uuid)))
ORDER BY
  CASE WHEN $4::boolean THEN created_at END ASC,
  CASE WHEN $4::boolean THEN id END ASC,
  CASE WHEN NOT $4::boolean THEN created_at END DESC,
  CASE WHEN NOT $4::boolean THEN id END DESC
LIMIT $6
`

type ListSourceFilesParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	Purpose      pgtype.Text        `json:"purpose"`
	AfterCreated pgtype.Timestamptz `json:"after_created"`
	Ascending    bool               `json:"ascending"`
	AfterID      pgtype.UUID        `json:"after_id"`
	PageLimit    int32              `json:"page_limit"`
}

func (q *Queries) ListSourceFiles(ctx context.Context, arg ListSourceFilesParams) ([]SourceFile, error) {
	rows, err := q.db.Query(ctx, listSourceFiles,
		arg.TenantID,
		arg.Purpose,
		arg.AfterCreated,
		arg.Ascending,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SourceFile{}
	for rows.Next() {
		var i SourceFile
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Filename,
			&i.Purpose,
			&i.BodyOid,
			&i.SizeBytes,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSourceFile = `-- name: LockSourceFile :one
SELECT id, tenant_id, filename, purpose, body_oid, size_bytes, sha256, created_at FROM source_files WHERE tenant_id = $1 AND id = $2 FOR SHARE
`

type LockSourceFileParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) LockSourceFile(ctx context.Context, arg LockSourceFileParams) (SourceFile, error) {
	row := q.db.QueryRow(ctx, lockSourceFile, arg.TenantID, arg.ID)
	var i SourceFile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Filename,
		&i.Purpose,
		&i.BodyOid,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}
