// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: workspaces.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateWorkspaceConfiguration = `-- name: ActivateWorkspaceConfiguration :exec
UPDATE workspace_fs_configurations SET active = true WHERE id = $1
`

func (q *Queries) ActivateWorkspaceConfiguration(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, activateWorkspaceConfiguration, id)
	return err
}

const beginWorkspaceDeletion = `-- name: BeginWorkspaceDeletion :execrows
UPDATE environment_workspaces SET state = 'deleting'
WHERE object_id = $1 AND state IN ('creating', 'ready')
`

func (q *Queries) BeginWorkspaceDeletion(ctx context.Context, objectID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, beginWorkspaceDeletion, objectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearActiveWorkspaceConfiguration = `-- name: ClearActiveWorkspaceConfiguration :exec
UPDATE workspace_fs_configurations SET active = false WHERE active
`

func (q *Queries) ClearActiveWorkspaceConfiguration(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearActiveWorkspaceConfiguration)
	return err
}

const getActiveWorkspaceConfiguration = `-- name: GetActiveWorkspaceConfiguration :one
SELECT id, adapter, parameters, active FROM workspace_fs_configurations WHERE active
`

func (q *Queries) GetActiveWorkspaceConfiguration(ctx context.Context) (WorkspaceFsConfiguration, error) {
	row := q.db.QueryRow(ctx, getActiveWorkspaceConfiguration)
	var i WorkspaceFsConfiguration
	err := row.Scan(
		&i.ID,
		&i.Adapter,
		&i.Parameters,
		&i.Active,
	)
	return i, err
}

const getEnvironmentWorkspace = `-- name: GetEnvironmentWorkspace :one
SELECT w.object_id, w.environment_id, w.configuration_id, w.state, w.attachment, c.id, c.adapter, c.parameters, c.active, s.tenant_id
FROM environment_workspaces w
JOIN workspace_fs_configurations c ON c.id = w.configuration_id
JOIN environments e ON e.id = w.environment_id
JOIN sessions s ON s.id = e.session_id
WHERE s.tenant_id = $1 AND e.id = $2
`

type GetEnvironmentWorkspaceParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetEnvironmentWorkspaceRow struct {
	EnvironmentWorkspace     EnvironmentWorkspace     `json:"environment_workspace"`
	WorkspaceFsConfiguration WorkspaceFsConfiguration `json:"workspace_fs_configuration"`
	TenantID                 pgtype.UUID              `json:"tenant_id"`
}

func (q *Queries) GetEnvironmentWorkspace(ctx context.Context, arg GetEnvironmentWorkspaceParams) (GetEnvironmentWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentWorkspace, arg.TenantID, arg.ID)
	var i GetEnvironmentWorkspaceRow
	err := row.Scan(
		&i.EnvironmentWorkspace.ObjectID,
		&i.EnvironmentWorkspace.EnvironmentID,
		&i.EnvironmentWorkspace.ConfigurationID,
		&i.EnvironmentWorkspace.State,
		&i.EnvironmentWorkspace.Attachment,
		&i.WorkspaceFsConfiguration.ID,
		&i.WorkspaceFsConfiguration.Adapter,
		&i.WorkspaceFsConfiguration.Parameters,
		&i.WorkspaceFsConfiguration.Active,
		&i.TenantID,
	)
	return i, err
}

const insertEnvironmentWorkspace = `-- name: InsertEnvironmentWorkspace :exec
INSERT INTO environment_workspaces (object_id, environment_id, configuration_id)
VALUES ($1, $2, $3)
`

type InsertEnvironmentWorkspaceParams struct {
	ObjectID        pgtype.UUID `json:"object_id"`
	EnvironmentID   pgtype.UUID `json:"environment_id"`
	ConfigurationID pgtype.UUID `json:"configuration_id"`
}

func (q *Queries) InsertEnvironmentWorkspace(ctx context.Context, arg InsertEnvironmentWorkspaceParams) error {
	_, err := q.db.Exec(ctx, insertEnvironmentWorkspace, arg.ObjectID, arg.EnvironmentID, arg.ConfigurationID)
	return err
}

const insertWorkspaceConfiguration = `-- name: InsertWorkspaceConfiguration :exec
INSERT INTO workspace_fs_configurations (id, adapter, parameters) VALUES ($1, $2, $3)
ON CONFLICT (id) DO NOTHING
`

type InsertWorkspaceConfigurationParams struct {
	ID         pgtype.UUID `json:"id"`
	Adapter    string      `json:"adapter"`
	Parameters []byte      `json:"parameters"`
}

func (q *Queries) InsertWorkspaceConfiguration(ctx context.Context, arg InsertWorkspaceConfigurationParams) error {
	_, err := q.db.Exec(ctx, insertWorkspaceConfiguration, arg.ID, arg.Adapter, arg.Parameters)
	return err
}

const listWorkspaceDeletionCandidates = `-- name: ListWorkspaceDeletionCandidates :many
SELECT w.object_id, w.environment_id, w.configuration_id, w.state, w.attachment, c.id, c.adapter, c.parameters, c.active, s.tenant_id
FROM environment_workspaces w
JOIN workspace_fs_configurations c ON c.id = w.configuration_id
JOIN environments e ON e.id = w.environment_id
JOIN sessions s ON s.id = e.session_id
WHERE w.object_id > $1 AND w.state <> 'deleted'
  AND (s.deleted_at IS NOT NULL OR w.state = 'deleting')
  AND NOT EXISTS (
      SELECT 1 FROM runtime_allocations a WHERE a.environment_id = e.id AND a.state <> 'released'
  )
ORDER BY w.object_id LIMIT 32
`

type ListWorkspaceDeletionCandidatesRow struct {
	EnvironmentWorkspace     EnvironmentWorkspace     `json:"environment_workspace"`
	WorkspaceFsConfiguration WorkspaceFsConfiguration `json:"workspace_fs_configuration"`
	TenantID                 pgtype.UUID              `json:"tenant_id"`
}

func (q *Queries) ListWorkspaceDeletionCandidates(ctx context.Context, objectID pgtype.UUID) ([]ListWorkspaceDeletionCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceDeletionCandidates, objectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceDeletionCandidatesRow{}
	for rows.Next() {
		var i ListWorkspaceDeletionCandidatesRow
		if err := rows.Scan(
			&i.EnvironmentWorkspace.ObjectID,
			&i.EnvironmentWorkspace.EnvironmentID,
			&i.EnvironmentWorkspace.ConfigurationID,
			&i.EnvironmentWorkspace.State,
			&i.EnvironmentWorkspace.Attachment,
			&i.WorkspaceFsConfiguration.ID,
			&i.WorkspaceFsConfiguration.Adapter,
			&i.WorkspaceFsConfiguration.Parameters,
			&i.WorkspaceFsConfiguration.Active,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkspaceConfigurations = `-- name: LockWorkspaceConfigurations :exec
LOCK TABLE workspace_fs_configurations IN SHARE ROW EXCLUSIVE MODE
`

func (q *Queries) LockWorkspaceConfigurations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockWorkspaceConfigurations)
	return err
}

const lockWorkspaceSession = `-- name: LockWorkspaceSession :one
SELECT s.id FROM sessions s JOIN environments e ON e.session_id = s.id
WHERE s.tenant_id = $1 AND e.id = $2 FOR UPDATE OF s
`

type LockWorkspaceSessionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) LockWorkspaceSession(ctx context.Context, arg LockWorkspaceSessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockWorkspaceSession, arg.TenantID, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const markWorkspaceDeleted = `-- name: MarkWorkspaceDeleted :execrows
UPDATE environment_workspaces SET state = 'deleted'
WHERE object_id = $1 AND state = 'deleting'
`

func (q *Queries) MarkWorkspaceDeleted(ctx context.Context, objectID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markWorkspaceDeleted, objectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markWorkspaceReady = `-- name: MarkWorkspaceReady :execrows
UPDATE environment_workspaces SET state = 'ready', attachment = $2
WHERE object_id = $1 AND state = 'creating'
`

type MarkWorkspaceReadyParams struct {
	ObjectID   pgtype.UUID `json:"object_id"`
	Attachment []byte      `json:"attachment"`
}

func (q *Queries) MarkWorkspaceReady(ctx context.Context, arg MarkWorkspaceReadyParams) (int64, error) {
	result, err := q.db.Exec(ctx, markWorkspaceReady, arg.ObjectID, arg.Attachment)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const matchWorkspaceConfiguration = `-- name: MatchWorkspaceConfiguration :one
SELECT (adapter = $1 AND parameters = $2::jsonb)::boolean AS matches
FROM workspace_fs_configurations WHERE id = $3
`

type MatchWorkspaceConfigurationParams struct {
	Adapter    string      `json:"adapter"`
	Parameters []byte      `json:"parameters"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) MatchWorkspaceConfiguration(ctx context.Context, arg MatchWorkspaceConfigurationParams) (bool, error) {
	row := q.db.QueryRow(ctx, matchWorkspaceConfiguration, arg.Adapter, arg.Parameters, arg.ID)
	var matches bool
	err := row.Scan(&matches)
	return matches, err
}

const workspaceComputeReleased = `-- name: WorkspaceComputeReleased :one
SELECT NOT EXISTS (
    SELECT 1 FROM runtime_allocations WHERE environment_id = $1 AND state <> 'released'
) AS released
`

func (q *Queries) WorkspaceComputeReleased(ctx context.Context, environmentID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, workspaceComputeReleased, environmentID)
	var released bool
	err := row.Scan(&released)
	return released, err
}

const workspaceSessionDeleted = `-- name: WorkspaceSessionDeleted :one
SELECT (deleted_at IS NOT NULL)::boolean AS deleted FROM sessions WHERE id = $1
`

func (q *Queries) WorkspaceSessionDeleted(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, workspaceSessionDeleted, id)
	var deleted bool
	err := row.Scan(&deleted)
	return deleted, err
}
