// Code generated by scripts/generate-harness-catalog.py; DO NOT EDIT.

export const coreHarnessKinds = ["claude_sdk", "codex", "mcode"] as const;
export type CoreHarnessKind = (typeof coreHarnessKinds)[number];
export const coreHarnessNames: Record<CoreHarnessKind, string> = {
  "claude_sdk": "Claude Code",
  "codex": "Codex",
  "mcode": "MiniMax Code",
};
export const modelProviderProtocols = ["anthropic", "responses", "chat_completions"] as const;
export type ModelProviderProtocol = (typeof modelProviderProtocols)[number];
