import type { vaults as english } from "../en/vaults";
type TranslationShape<T> = { [K in keyof T]: T[K] extends string ? string : TranslationShape<T[K]> };
export const vaults: TranslationShape<typeof english> = {
  securityNote: "令牌只可写入。此页面只接收 Credential 元数据，绝不会接收令牌值。删除 Vault 也会删除其中保存的所有 Credential，但不会撤销 provider 侧令牌。",
  actionNotConfirmed: "操作未确认", mutationUncertain: "未能确认写入结果。目录已刷新；再次明确重试前请检查当前 Core 状态。", loading: "正在加载 Vault", loadFailed: "无法加载 Vault", refreshFailed: "无法刷新 Vault", failedDescription: "Web 无法加载完整的 Vault 和 Credential 目录。", staleDescription: "之前的安全元数据快照仍可见，但不能授权新 Session。", failedHint: "请检查 Core 连接后刷新。在完整目录加载前，需要 Credential 的 Session 会保持阻止状态。",
  credential: "Credential", deleteVaultLabel: "删除 {{name}}", created: "创建时间", credentialsIn: "{{name}} 中的 Credential", updatedHidden: "更新于 {{date}} · 令牌已隐藏", oauthHelp: "OAuth · 请在你的应用中管理授权和令牌替换。", replaceTokenLabel: "替换 {{name}} 的令牌", replaceToken: "替换令牌", deleteCredentialLabel: "删除 {{name}}", noCredentials: "此 Vault 中没有 Credential。", noVaults: "没有 Vault", noVaultsDescription: "请先创建 Vault，再添加只写的静态 bearer Credential。", createVault: "创建 Vault", createVaultTitle: "创建 Vault", deleteVaultTitle: "删除 Vault？", deleteCredentialTitle: "删除 Credential？", deleting: "删除中…", delete: "删除", deleteVaultPrompt: "删除 {{name}} 及其中保存的全部 Credential？现有 Session 会保留冻结的 ID，但后续密钥读取会失败。Provider 令牌和正在运行的工作不会被撤销。", deleteCredentialPrompt: "删除 {{name}}？现有 Session 会保留其冻结标识，但后续密钥读取会失败。此操作不会撤销 MCP provider 上的令牌。", unnamed: "未命名 Vault",
  list: { label: "Vault", filterLabel: "筛选 Vault", filterPlaceholder: "按名称或 ID 筛选", name: "名称", credentials: "Credential", created: "创建时间", actions: "操作", open: "打开 {{name}}", noMatch: "没有匹配的 Vault" },
  detail: { back: "返回", facts: "Vault 详情", id: "ID", created: "创建时间", metadata: "元数据", credentials: "Credential", credentialsHelp: "静态 bearer 令牌只可写入：Core 不会返回令牌，所以这里只显示元数据。替换令牌不会在 provider 侧撤销旧令牌。", name: "名称", url: "MCP 服务 URL", auth: "认证方式", updated: "更新时间", addCredential: "添加 Credential", deleteVault: "删除 Vault", staticBearer: "静态 bearer", oauth: "OAuth", tokenHidden: "令牌已隐藏" },
  createForm: { name: "名称", namePlaceholder: "运行时 Credential", nameHelp: "必填。去除首尾空格后的名称最多 256 个 UTF-8 字节。", metadata: "元数据", optional: "可选", metadataHelp: "输入值为字符串的 JSON 对象。留空会转为 {{emptyObject}}；编码后的元数据最大为 64 KiB。", metadataWarning: "Vault 元数据是公开的。切勿在此填写密钥、令牌、密码、凭据或私有连接信息。", creating: "创建中…", create: "创建 Vault" },
  credentialDialog: { replaceTitle: "替换令牌 · {{name}}", addTitle: "添加静态 bearer Credential", saving: "保存中…", create: "创建 Credential", notConfirmed: "Credential 未确认", name: "名称", namePlaceholder: "内部 MCP", exactUrl: "精确 MCP 服务 URL", urlHelp: "此 URL 必须与 Agent MCP 定义完全一致。创建此资源不会发起网络请求。", replaceWarning: "旧令牌不会被读取或显示。正在运行的工作可能已经持有它；替换操作不会撤销 provider 侧令牌。", newToken: "新 bearer 令牌", token: "Bearer 令牌", tokenHelp: "只可写入。令牌只发送一次，随后立即清除，且绝不会保存到浏览器状态、元数据、预览或日志中。" },
  errors: { auth: "Core 认证失败，Credential 未确认。", missing: "Vault 或 Credential 已不存在。请刷新后重试。", tooLarge: "Credential 请求超过 Core 接受的大小。", invalidFields: "Core 拒绝了 Credential 字段。请检查名称、精确 HTTPS URL 和令牌格式。", credentialUncertain: "未能确认 Credential 写入结果。目录已刷新；再次明确重试前请先检查。", bearer: "请输入非空的 RFC 6750 bearer 令牌。空白或其他仅能保存的不透明值无法在当前运行时执行。", credentialName: "Credential 名称必须为 1 至 256 个 UTF-8 字节。", exactUrl: "请输入不含凭据、查询参数、片段、空白或反斜杠的精确 HTTPS MCP URL。", createUncertain: "未能确认 Vault 创建结果。草稿保持不变；再次明确重试前请检查当前 Core 状态。", vaultName: "名称必须为 1 至 256 个 UTF-8 字节。", metadataUnknown: "无法验证元数据。", metadataJson: "元数据必须是有效 JSON。", metadataShape: "元数据必须是值为字符串的 JSON 对象。", metadataStrings: "元数据值必须全部为字符串；不支持嵌套值、数组、数字、布尔值和 null。", metadataLarge: "元数据经 UTF-8 JSON 编码后最大为 64 KiB。", mismatchedMetadata: "OpenAgentCore 返回的 Vault 元数据不匹配。", uniqueAttachments: "附加的 Vault 不能重复。", catalogIncomplete: "尚未从此 Core 完整加载 Credential 元数据。", vaultMissing: "所选 Vault 已不在当前目录中。", credentialMismatch: "MCP 服务 {{server}} 引用了不可用或 URL 不匹配的 Credential。", credentialVaultMissing: "MCP 服务 {{server}} 引用的 Credential 所属 Vault 不可用。", multipleCredentials: "匿名 MCP 服务 {{server}} 在所选 Vault 中匹配到多个 Credential。请选择唯一匹配的 Vault，或明确配置一个 Credential。", matchedVaultMissing: "MCP 服务 {{server}} 匹配到的 Credential 所属 Vault 不可用。" },
};
