// Code generated by scripts/generate-public-api.py; DO NOT EDIT.
package api

// Pinned request shapes; x_agents_core is checked by its own parser.
var (
	createAgentParams = shape{kind: objectValue, members: []member{
		{"metadata", shape{kind: mapValue, items: &shape{kind: stringValue}, nullable: true}},
		{"name", shape{kind: stringValue, nullable: true}},
		{"model", shape{kind: stringValue, required: true}},
		{"reasoning", shape{kind: objectValue, members: []member{
			{"effort", shape{kind: enumValue, values: []string{"none", "minimal", "low", "medium", "high", "xhigh", "max"}, nullable: true}},
			{"summary", shape{kind: enumValue, values: []string{"concise", "detailed", "auto"}, nullable: true}},
		}, nullable: true}},
		{"text", shape{kind: objectValue, members: []member{
			{"format", shape{kind: unionValue, values: []string{"text", "json_schema"}, variants: map[string][]member{
				"text": {},
				"json_schema": {
					{"schema", shape{kind: mapValue, required: true}},
				},
			}, nullable: true}},
			{"verbosity", shape{kind: enumValue, values: []string{"low", "medium", "high"}, nullable: true}},
		}, nullable: true}},
		{"service_tier", shape{kind: enumValue, values: []string{"auto", "default", "flex", "priority", "fast"}, nullable: true}},
		{"instructions", shape{kind: stringValue, nullable: true}},
		{"tools", shape{kind: arrayValue, items: &shape{kind: unionValue, values: []string{"function", "tool_search", "programmatic_tool_calling", "mcp", "web_search"}, variants: map[string][]member{
			"function": {
				{"name", shape{kind: stringValue, required: true}},
				{"description", shape{kind: stringValue, required: true}},
				{"parameters", shape{kind: mapValue, required: true}},
				{"defer_loading", shape{kind: booleanValue}},
			},
			"tool_search": {},
			"programmatic_tool_calling": {
				{"enabled", shape{kind: booleanValue}},
			},
			"mcp": {
				{"server_label", shape{kind: stringValue, required: true}},
				{"credential_id", shape{kind: stringValue, nullable: true}},
				{"transport", shape{kind: unionValue, values: []string{"http", "stdio"}, variants: map[string][]member{
					"http": {
						{"server_url", shape{kind: stringValue, required: true}},
						{"headers", shape{kind: mapValue, items: &shape{kind: stringValue}, nullable: true}},
					},
					"stdio": {
						{"command", shape{kind: stringValue, required: true}},
						{"args", shape{kind: arrayValue, items: &shape{kind: stringValue}, nullable: true}},
						{"cwd", shape{kind: stringValue, required: true}},
						{"env_vars", shape{kind: arrayValue, items: &shape{kind: stringValue}, nullable: true}},
					},
				}, required: true}},
				{"request_metadata", shape{kind: mapValue, nullable: true}},
				{"allowed_tools", shape{kind: arrayValue, items: &shape{kind: stringValue}, nullable: true}},
				{"required", shape{kind: booleanValue}},
				{"connection_origin", shape{kind: enumValue, values: []string{"service", "environment"}, nullable: true}},
			},
			"web_search": {
				{"mode", shape{kind: enumValue, values: []string{"disabled", "cached", "live"}, nullable: true}},
				{"context_size", shape{kind: enumValue, values: []string{"low", "medium", "high"}, nullable: true}},
				{"allowed_domains", shape{kind: arrayValue, items: &shape{kind: stringValue}, nullable: true}},
				{"location", shape{kind: objectValue, members: []member{
					{"country", shape{kind: stringValue, nullable: true}},
					{"region", shape{kind: stringValue, nullable: true}},
					{"city", shape{kind: stringValue, nullable: true}},
					{"timezone", shape{kind: stringValue, nullable: true}},
				}, nullable: true}},
			},
		}}, nullable: true}},
		{"multi_agent", shape{kind: objectValue, members: []member{
			{"enabled", shape{kind: booleanValue, required: true}},
			{"max_concurrent_subagents", shape{kind: integerValue, minimum: 1}},
		}, nullable: true}},
		{"x_agents_core", shape{}},
	}}
	updateAgentParams = shape{kind: objectValue, members: []member{
		{"model", shape{kind: stringValue}},
		{"reasoning", shape{kind: objectValue, members: []member{
			{"effort", shape{kind: enumValue, values: []string{"none", "minimal", "low", "medium", "high", "xhigh", "max"}, nullable: true}},
			{"summary", shape{kind: enumValue, values: []string{"concise", "detailed", "auto"}, nullable: true}},
		}, nullable: true}},
		{"text", shape{kind: objectValue, members: []member{
			{"format", shape{kind: unionValue, values: []string{"text", "json_schema"}, variants: map[string][]member{
				"text": {},
				"json_schema": {
					{"schema", shape{kind: mapValue, required: true}},
				},
			}, nullable: true}},
			{"verbosity", shape{kind: enumValue, values: []string{"low", "medium", "high"}, nullable: true}},
		}, nullable: true}},
		{"service_tier", shape{kind: enumValue, values: []string{"auto", "default", "flex", "priority", "fast"}, nullable: true}},
		{"instructions", shape{kind: stringValue, nullable: true}},
		{"multi_agent", shape{kind: objectValue, members: []member{
			{"enabled", shape{kind: booleanValue, required: true}},
			{"max_concurrent_subagents", shape{kind: integerValue, minimum: 1}},
		}, nullable: true}},
		{"metadata", shape{kind: mapValue, items: &shape{kind: stringValue}, nullable: true}},
		{"name", shape{kind: stringValue, nullable: true}},
		{"tools", shape{kind: arrayValue, items: &shape{kind: unionValue, values: []string{"function", "tool_search", "programmatic_tool_calling", "mcp", "web_search"}, variants: map[string][]member{
			"function": {
				{"name", shape{kind: stringValue, required: true}},
				{"description", shape{kind: stringValue, required: true}},
				{"parameters", shape{kind: mapValue, required: true}},
				{"defer_loading", shape{kind: booleanValue}},
			},
			"tool_search": {},
			"programmatic_tool_calling": {
				{"enabled", shape{kind: booleanValue}},
			},
			"mcp": {
				{"server_label", shape{kind: stringValue, required: true}},
				{"credential_id", shape{kind: stringValue, nullable: true}},
				{"transport", shape{kind: unionValue, values: []string{"http", "stdio"}, variants: map[string][]member{
					"http": {
						{"server_url", shape{kind: stringValue, required: true}},
						{"headers", shape{kind: mapValue, items: &shape{kind: stringValue}, nullable: true}},
					},
					"stdio": {
						{"command", shape{kind: stringValue, required: true}},
						{"args", shape{kind: arrayValue, items: &shape{kind: stringValue}, nullable: true}},
						{"cwd", shape{kind: stringValue, required: true}},
						{"env_vars", shape{kind: arrayValue, items: &shape{kind: stringValue}, nullable: true}},
					},
				}, required: true}},
				{"request_metadata", shape{kind: mapValue, nullable: true}},
				{"allowed_tools", shape{kind: arrayValue, items: &shape{kind: stringValue}, nullable: true}},
				{"required", shape{kind: booleanValue}},
				{"connection_origin", shape{kind: enumValue, values: []string{"service", "environment"}, nullable: true}},
			},
			"web_search": {
				{"mode", shape{kind: enumValue, values: []string{"disabled", "cached", "live"}, nullable: true}},
				{"context_size", shape{kind: enumValue, values: []string{"low", "medium", "high"}, nullable: true}},
				{"allowed_domains", shape{kind: arrayValue, items: &shape{kind: stringValue}, nullable: true}},
				{"location", shape{kind: objectValue, members: []member{
					{"country", shape{kind: stringValue, nullable: true}},
					{"region", shape{kind: stringValue, nullable: true}},
					{"city", shape{kind: stringValue, nullable: true}},
					{"timezone", shape{kind: stringValue, nullable: true}},
				}, nullable: true}},
			},
		}}, nullable: true}},
		{"x_agents_core", shape{}},
	}}
	sessionAgentConfigParam = shape{kind: objectValue, members: []member{
		{"model", shape{kind: stringValue}},
		{"reasoning", shape{kind: objectValue, members: []member{
			{"effort", shape{kind: enumValue, values: []string{"none", "minimal", "low", "medium", "high", "xhigh", "max"}, nullable: true}},
			{"summary", shape{kind: enumValue, values: []string{"concise", "detailed", "auto"}, nullable: true}},
		}, nullable: true}},
		{"text", shape{kind: objectValue, members: []member{
			{"format", shape{kind: unionValue, values: []string{"text", "json_schema"}, variants: map[string][]member{
				"text": {},
				"json_schema": {
					{"schema", shape{kind: mapValue, required: true}},
				},
			}, nullable: true}},
			{"verbosity", shape{kind: enumValue, values: []string{"low", "medium", "high"}, nullable: true}},
		}, nullable: true}},
		{"service_tier", shape{kind: enumValue, values: []string{"auto", "default", "flex", "priority", "fast"}, nullable: true}},
		{"instructions", shape{kind: stringValue, nullable: true}},
		{"multi_agent", shape{kind: objectValue, members: []member{
			{"enabled", shape{kind: booleanValue, required: true}},
			{"max_concurrent_subagents", shape{kind: integerValue, minimum: 1}},
		}, nullable: true}},
		{"tools", shape{kind: arrayValue, items: &shape{kind: unionValue, values: []string{"function", "tool_search", "programmatic_tool_calling", "mcp", "web_search"}, variants: map[string][]member{
			"function": {
				{"name", shape{kind: stringValue, required: true}},
				{"description", shape{kind: stringValue, required: true}},
				{"parameters", shape{kind: mapValue, required: true}},
				{"defer_loading", shape{kind: booleanValue}},
			},
			"tool_search": {},
			"programmatic_tool_calling": {
				{"enabled", shape{kind: booleanValue}},
			},
			"mcp": {
				{"server_label", shape{kind: stringValue, required: true}},
				{"credential_id", shape{kind: stringValue, nullable: true}},
				{"transport", shape{kind: unionValue, values: []string{"http", "stdio"}, variants: map[string][]member{
					"http": {
						{"server_url", shape{kind: stringValue, required: true}},
						{"authorization", shape{kind: stringValue, nullable: true}},
						{"headers", shape{kind: mapValue, items: &shape{kind: stringValue}, nullable: true}},
					},
					"stdio": {
						{"command", shape{kind: stringValue, required: true}},
						{"args", shape{kind: arrayValue, items: &shape{kind: stringValue}, nullable: true}},
						{"cwd", shape{kind: stringValue, required: true}},
						{"env", shape{kind: mapValue, items: &shape{kind: stringValue}, nullable: true}},
						{"env_vars", shape{kind: arrayValue, items: &shape{kind: stringValue}, nullable: true}},
					},
				}, required: true}},
				{"request_metadata", shape{kind: mapValue, nullable: true}},
				{"allowed_tools", shape{kind: arrayValue, items: &shape{kind: stringValue}, nullable: true}},
				{"required", shape{kind: booleanValue}},
				{"connection_origin", shape{kind: enumValue, values: []string{"service", "environment"}, nullable: true}},
			},
			"web_search": {
				{"mode", shape{kind: enumValue, values: []string{"disabled", "cached", "live"}, nullable: true}},
				{"context_size", shape{kind: enumValue, values: []string{"low", "medium", "high"}, nullable: true}},
				{"allowed_domains", shape{kind: arrayValue, items: &shape{kind: stringValue}, nullable: true}},
				{"location", shape{kind: objectValue, members: []member{
					{"country", shape{kind: stringValue, nullable: true}},
					{"region", shape{kind: stringValue, nullable: true}},
					{"city", shape{kind: stringValue, nullable: true}},
					{"timezone", shape{kind: stringValue, nullable: true}},
				}, nullable: true}},
			},
		}}, nullable: true}},
		{"x_agents_core", shape{}},
	}}
)
