// provider-artifacts generates distribution declarations from registered adapters.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"strconv"

	"github.com/MiniMax-AI/OpenAgentCore/services/core/internal/sandbox/providers"
)

func main() {
	write := flag.Bool("write", false, "write generated declarations from the repository root")
	flag.Parse()
	catalog, err := providers.Builtin().ArtifactCatalog()
	if err != nil {
		panic(err)
	}
	raw, err := json.MarshalIndent(catalog, "", "  ")
	if err != nil {
		panic(err)
	}
	raw = append(raw, '\n')
	python := []byte("# Code generated by go run ./services/core/cmd/provider-artifacts -write; DO NOT EDIT.\nimport json\n\nCATALOG = json.loads(" + strconv.Quote(string(raw)) + ")\n\ndef artifacts(provider, roles=None):\n    return tuple(item[\"path\"] for item in CATALOG[provider] if roles is None or item[\"role\"] in roles)\n")
	for path, content := range map[string][]byte{"internal/providerassets/catalog.json": raw, "deploy/node/provider_assets.py": python} {
		if *write {
			err = os.WriteFile(path, content, 0644)
		} else {
			var current []byte
			current, err = os.ReadFile(path)
			if err == nil && string(current) != string(content) {
				err = fmt.Errorf("stale generated file: %s", path)
			}
		}
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
	}
}
