# Code generated by scripts/generate-harness-catalog.py; DO NOT EDIT.
# Provider support comes from the adapter-owned Go configuration declarations.
PROVIDERS = {'claude_sdk': {'anthropic': {'requires_token_limits': False}},
 'codex': {'responses': {'requires_token_limits': False}},
 'mcode': {'anthropic': {'requires_token_limits': True},
           'chat_completions': {'requires_token_limits': True},
           'responses': {'requires_token_limits': True}}}
