// Code generated by scripts/generate-public-api.py; DO NOT EDIT.
package v1

import "encoding/json"

import "fmt"

// APIError projects Error.
type APIError struct {
	Message      string          `json:"message" binding:"required"`
	Type         string          `json:"type" binding:"required"`
	Code         *string         `json:"code" binding:"required" extensions:"x-nullable"`
	Param        *string         `json:"param" binding:"required" extensions:"x-nullable"`
	Misalignment json.RawMessage `json:"misalignment,omitempty" swaggertype:"object"`
}

// Agent projects SessionAgentResource.
type Agent struct {
	XAgentsCore  *AgentsCore       `json:"x_agents_core,omitempty"`
	ID           string            `json:"id" binding:"required"`
	Instructions *string           `json:"instructions" binding:"required" extensions:"x-nullable"`
	Model        string            `json:"model" binding:"required"`
	MultiAgent   MultiAgentConfig  `json:"multi_agent" binding:"required"`
	Name         *string           `json:"name" binding:"required" extensions:"x-nullable"`
	Reasoning    Reasoning         `json:"reasoning" binding:"required"`
	ServiceTier  string            `json:"service_tier" binding:"required" enums:"auto,default,flex,priority,fast"`
	Text         TextConfig        `json:"text" binding:"required"`
	Tools        []json.RawMessage `json:"tools" binding:"required" swaggertype:"array,object"`
}

// AgentContent projects AgentContentResource.
type AgentContent struct {
	Type             string  `json:"type" binding:"required" enums:"output_text,encrypted_content"`
	Text             *string `json:"text,omitempty"`
	EncryptedContent *string `json:"encrypted_content,omitempty"`
}

// AgentDeleted projects DeletedAgentResource.
type AgentDeleted struct {
	ID      string `json:"id" binding:"required"`
	Object  string `json:"object" binding:"required" enums:"agent.deleted"`
	Deleted bool   `json:"deleted" binding:"required"`
}

// AgentMessageItem projects AgentMessageItemResource.
type AgentMessageItem struct {
	ID               string         `json:"id" binding:"required"`
	TurnID           string         `json:"turn_id" binding:"required"`
	Type             string         `json:"type" binding:"required" enums:"agent_message"`
	SenderAgentID    string         `json:"sender_agent_id" binding:"required"`
	RecipientAgentID string         `json:"recipient_agent_id" binding:"required"`
	Content          []AgentContent `json:"content" binding:"required"`
}

// CreateAgentRequest projects CreateAgentParams.
type CreateAgentRequest struct {
	XAgentsCore  *SavedAgentCoreInput `json:"x_agents_core,omitempty"`
	Model        *string              `json:"model" binding:"required"`
	Name         *string              `json:"name,omitempty" extensions:"x-nullable"`
	Instructions *string              `json:"instructions,omitempty" extensions:"x-nullable"`
	Metadata     map[string]*string   `json:"metadata,omitempty" extensions:"x-nullable"`
	MultiAgent   json.RawMessage      `json:"multi_agent,omitempty" extensions:"x-nullable" swaggertype:"object"`
	Reasoning    *Reasoning           `json:"reasoning,omitempty" extensions:"x-nullable"`
	ServiceTier  *string              `json:"service_tier,omitempty" extensions:"x-nullable" enums:"auto,default,flex,priority,fast"`
	Text         *TextConfigInput     `json:"text,omitempty" extensions:"x-nullable"`
	Tools        []json.RawMessage    `json:"tools,omitempty" extensions:"x-nullable" swaggertype:"array,object"`
}

// CreateSessionRequest projects CreateAgentSessionParams.
type CreateSessionRequest struct {
	XAgentsCore *SessionExecutionInput `json:"x_agents_core,omitempty"`
	Agent       *InlineAgent           `json:"agent,omitempty"`
	AgentID     *string                `json:"agent_id,omitempty"`
	Environment *Environment           `json:"environment" binding:"required"`
	Input       any                    `json:"input,omitempty" extensions:"x-nullable"`
	Metadata    map[string]string      `json:"metadata,omitempty" extensions:"x-nullable"`
	Stream      bool                   `json:"stream,omitempty"`
	VaultIDs    []string               `json:"vault_ids,omitempty" extensions:"x-nullable"`
}

// CreateSubagentCallItem projects CreateSubagentCallItemResource.
type CreateSubagentCallItem struct {
	ID              string         `json:"id" binding:"required"`
	TurnID          string         `json:"turn_id" binding:"required"`
	Type            string         `json:"type" binding:"required" enums:"create_subagent_call"`
	Status          string         `json:"status" binding:"required" enums:"in_progress,completed,failed,incomplete"`
	AgentID         string         `json:"agent_id" binding:"required"`
	Content         []AgentContent `json:"content" binding:"required"`
	Model           *string        `json:"model" binding:"required" extensions:"x-nullable"`
	ReasoningEffort *string        `json:"reasoning_effort" binding:"required" extensions:"x-nullable"`
}

// Credential projects VaultCredentialResource.
type Credential struct {
	ID        string         `json:"id" binding:"required"`
	VaultID   string         `json:"vault_id" binding:"required"`
	Name      string         `json:"name" binding:"required"`
	Object    string         `json:"object" binding:"required" enums:"vault.credential"`
	Auth      CredentialAuth `json:"auth" binding:"required"`
	CreatedAt int64          `json:"created_at" binding:"required"`
	UpdatedAt int64          `json:"updated_at" binding:"required"`
}

// CredentialAuth projects VaultCredentialAuthResource.
type CredentialAuth struct {
	Type         string                  `json:"type" binding:"required" enums:"mcp_oauth,static_bearer"`
	MCPServerURL string                  `json:"mcp_server_url" binding:"required"`
	ExpiresAt    *string                 `json:"expires_at" extensions:"x-nullable"`
	Refresh      *OAuthCredentialRefresh `json:"refresh" extensions:"x-nullable"`
}

// CredentialAuthInput projects CreateVaultCredentialAuthParam.
type CredentialAuthInput struct {
	Type         string                       `json:"type" binding:"required" enums:"mcp_oauth,static_bearer"`
	MCPServerURL *string                      `json:"mcp_server_url" binding:"required"`
	Token        *string                      `json:"token,omitempty"`
	AccessToken  *string                      `json:"access_token,omitempty"`
	ExpiresAt    *string                      `json:"expires_at,omitempty" extensions:"x-nullable"`
	Refresh      *OAuthCredentialRefreshInput `json:"refresh,omitempty" extensions:"x-nullable"`
}

// CredentialAuthReplacement projects RotateVaultCredentialAuthParam.
type CredentialAuthReplacement struct {
	Type        string                             `json:"type" binding:"required" enums:"mcp_oauth,static_bearer"`
	Token       *string                            `json:"token,omitempty"`
	AccessToken *string                            `json:"access_token,omitempty" extensions:"x-nullable"`
	ExpiresAt   json.RawMessage                    `json:"expires_at,omitempty" extensions:"x-nullable" swaggertype:"object"`
	Refresh     *OAuthCredentialRefreshReplacement `json:"refresh,omitempty" extensions:"x-nullable"`
}

// CredentialDeleted projects DeletedVaultCredentialResource.
type CredentialDeleted struct {
	ID      string `json:"id" binding:"required"`
	Deleted bool   `json:"deleted" binding:"required"`
	Object  string `json:"object" binding:"required" enums:"vault.credential.deleted"`
}

// CredentialList projects VaultCredentialListResource.
type CredentialList struct {
	Object  string       `json:"object" binding:"required" enums:"list"`
	Data    []Credential `json:"data" binding:"required"`
	HasMore bool         `json:"has_more" binding:"required"`
	FirstID *string      `json:"first_id" binding:"required" extensions:"x-nullable"`
	LastID  *string      `json:"last_id" binding:"required" extensions:"x-nullable"`
}

// Environment projects EnvironmentParam.
type Environment struct {
	Plugins               []json.RawMessage        `json:"plugins,omitempty" extensions:"x-nullable" swaggertype:"array,object"`
	Skills                []json.RawMessage        `json:"skills,omitempty" extensions:"x-nullable" swaggertype:"array,object"`
	Env                   map[string]string        `json:"env,omitempty" extensions:"x-nullable"`
	SetupCommands         []json.RawMessage        `json:"setup_commands,omitempty" extensions:"x-nullable" swaggertype:"array,object"`
	Packages              *EnvironmentPackages     `json:"packages,omitempty" extensions:"x-nullable"`
	Files                 []json.RawMessage        `json:"files,omitempty" extensions:"x-nullable" swaggertype:"array,object"`
	EnvironmentTemplateID string                   `json:"environment_template_id,omitempty"`
	Type                  string                   `json:"type" binding:"required" enums:"none,openai_hosted,self_hosted"`
	WorkspaceDirectory    string                   `json:"workspace_directory,omitempty"`
	CapabilityDirectories []string                 `json:"capability_directories,omitempty" extensions:"x-nullable"`
	Network               *EnvironmentNetworkInput `json:"network,omitempty" extensions:"x-nullable"`
}

// EnvironmentConnectionAction projects SessionRequiredActionResourceEnvironmentConnection.
type EnvironmentConnectionAction struct {
	EnvironmentID string `json:"environment_id" binding:"required"`
	Type          string `json:"type" binding:"required" enums:"environment_connection"`
}

// EnvironmentFile projects EnvironmentFileResource.
type EnvironmentFile struct {
	EnvironmentID string `json:"environment_id" binding:"required"`
	Object        string `json:"object" binding:"required" enums:"agent.environment.file"`
	Path          string `json:"path" binding:"required"`
	SizeBytes     int64  `json:"size_bytes" binding:"required"`
}

// EnvironmentFileCreateRequest projects HostedEnvironmentFileParam.
type EnvironmentFileCreateRequest struct {
	Type   string  `json:"type" binding:"required" enums:"file_id,inline"`
	Data   *string `json:"data,omitempty"`
	FileID *string `json:"file_id,omitempty"`
	Path   *string `json:"path" binding:"required"`
}

// EnvironmentFileList projects EnvironmentFileListResource.
type EnvironmentFileList struct {
	Object  string            `json:"object" binding:"required" enums:"page"`
	Data    []EnvironmentFile `json:"data" binding:"required"`
	Next    *string           `json:"next" binding:"required" extensions:"x-nullable"`
	HasMore bool              `json:"has_more" binding:"required"`
}

// EnvironmentInfo projects PublicEnvironmentResource.
type EnvironmentInfo struct {
	ID      string            `json:"id" binding:"required"`
	Object  string            `json:"object" binding:"required" enums:"agent.environment"`
	Type    string            `json:"type" binding:"required" enums:"openai_hosted,self_hosted"`
	Status  string            `json:"status" binding:"required" enums:"pending,connected,disconnected,expired,failed"`
	Files   []json.RawMessage `json:"files" binding:"required" swaggertype:"array,object"`
	Plugins []json.RawMessage `json:"plugins" binding:"required" swaggertype:"array,object"`
	Skills  []json.RawMessage `json:"skills" binding:"required" swaggertype:"array,object"`
}

// EnvironmentNetwork projects NetworkPolicyResource.
type EnvironmentNetwork struct {
	Access         string   `json:"access" binding:"required" enums:"enabled,disabled,restricted"`
	AllowedDomains []string `json:"allowed_domains" binding:"required"`
}

// EnvironmentNetworkInput projects NetworkPolicyParam.
type EnvironmentNetworkInput struct {
	Access         string   `json:"access" binding:"required" enums:"enabled,disabled,restricted"`
	AllowedDomains []string `json:"allowed_domains,omitempty" extensions:"x-nullable"`
}

// EnvironmentPackages projects EnvironmentPackagesParam.
type EnvironmentPackages struct {
	NPM    []string `json:"npm" extensions:"x-nullable"`
	Python []string `json:"python" extensions:"x-nullable"`
}

// EnvironmentPackagesResponse projects EnvironmentPackagesResource.
type EnvironmentPackagesResponse struct {
	NPM    []string `json:"npm" binding:"required"`
	Python []string `json:"python" binding:"required"`
	System []string `json:"system" binding:"required"`
}

// EnvironmentTemplate projects EnvironmentTemplateResource.
type EnvironmentTemplate struct {
	ID                    string                      `json:"id" binding:"required"`
	Object                string                      `json:"object" binding:"required" enums:"agent.environment.template"`
	Name                  *string                     `json:"name" binding:"required" extensions:"x-nullable"`
	CreatedAt             int64                       `json:"created_at" binding:"required"`
	UpdatedAt             int64                       `json:"updated_at" binding:"required"`
	CapabilityDirectories []string                    `json:"capability_directories" binding:"required"`
	Network               EnvironmentNetwork          `json:"network" binding:"required"`
	Packages              EnvironmentPackagesResponse `json:"packages" binding:"required"`
	Files                 []json.RawMessage           `json:"files" binding:"required" swaggertype:"array,object"`
	Plugins               []json.RawMessage           `json:"plugins" binding:"required" swaggertype:"array,object"`
	Skills                []json.RawMessage           `json:"skills" binding:"required" swaggertype:"array,object"`
}

// EnvironmentTemplateDeleted projects DeletedEnvironmentTemplateResource.
type EnvironmentTemplateDeleted struct {
	ID      string `json:"id" binding:"required"`
	Object  string `json:"object" binding:"required" enums:"agent.environment.template.deleted"`
	Deleted bool   `json:"deleted" binding:"required"`
}

// EnvironmentTemplateList projects EnvironmentTemplateListResource.
type EnvironmentTemplateList struct {
	Object  string                `json:"object" binding:"required" enums:"list"`
	Data    []EnvironmentTemplate `json:"data" binding:"required"`
	HasMore bool                  `json:"has_more" binding:"required"`
	FirstID *string               `json:"first_id" binding:"required" extensions:"x-nullable"`
	LastID  *string               `json:"last_id" binding:"required" extensions:"x-nullable"`
}

// ErrorResponse projects ErrorResponse-2.
type ErrorResponse struct {
	Error APIError `json:"error" binding:"required"`
}

// FunctionCallAction projects SessionRequiredActionResourceFunctionCall.
type FunctionCallAction struct {
	Arguments any    `json:"arguments" binding:"required"`
	CallID    string `json:"call_id" binding:"required"`
	Name      string `json:"name" binding:"required"`
	TurnID    string `json:"turn_id" binding:"required"`
	Type      string `json:"type" binding:"required" enums:"function_call"`
}

// FunctionToolInput projects AgentToolConfigParamFunction.
type FunctionToolInput struct {
	Type         string          `json:"type" binding:"required" enums:"function"`
	Name         *string         `json:"name" binding:"required"`
	Description  *string         `json:"description" binding:"required"`
	Parameters   json.RawMessage `json:"parameters" binding:"required" swaggertype:"object"`
	DeferLoading json.RawMessage `json:"defer_loading,omitempty" swaggertype:"object"`
}

// InlineAgent projects SessionAgentConfigParam.
type InlineAgent struct {
	XAgentsCore  *AgentsCore       `json:"x_agents_core,omitempty"`
	Model        *string           `json:"model,omitempty"`
	Instructions *string           `json:"instructions,omitempty" extensions:"x-nullable"`
	MultiAgent   json.RawMessage   `json:"multi_agent,omitempty" extensions:"x-nullable" swaggertype:"object"`
	Reasoning    *Reasoning        `json:"reasoning,omitempty" extensions:"x-nullable"`
	ServiceTier  *string           `json:"service_tier,omitempty" extensions:"x-nullable" enums:"auto,default,flex,priority,fast"`
	Text         *TextConfigInput  `json:"text,omitempty" extensions:"x-nullable"`
	Tools        []json.RawMessage `json:"tools,omitempty" extensions:"x-nullable" swaggertype:"array,object"`
}

// InputContent projects InputContentParam.
type InputContent struct {
	Type     string  `json:"type" binding:"required" enums:"input_text,input_image"`
	Text     *string `json:"text,omitempty"`
	ImageURL *string `json:"image_url,omitempty"`
}

// InputMessage projects InputMessageParam.
type InputMessage struct {
	Type    string         `json:"type,omitempty" enums:"message"`
	Role    string         `json:"role" binding:"required" enums:"user"`
	Content []InputContent `json:"content" binding:"required"`
}

// InputTokenDetails projects InputTokensDetailsResource.
type InputTokenDetails struct {
	CachedTokens int64 `json:"cached_tokens" binding:"required"`
}

// Item projects SessionTurnItemResource.
type Item struct {
	ID                string           `json:"id" binding:"required" extensions:"x-nullable"`
	TurnID            string           `json:"turn_id" binding:"required"`
	Type              string           `json:"type" binding:"required" enums:"message,reasoning,function_call,function_call_output,agent_message,mcp_call,web_search_call,command_execution,create_subagent_call,send_subagent_input_call,resume_subagent_call,wait_for_subagents_call,interrupt_subagent_call,close_subagent_call"`
	Status            string           `json:"status" extensions:"x-nullable" enums:"in_progress,completed,incomplete,failed"`
	Role              string           `json:"role,omitempty" enums:"user,assistant"`
	Phase             string           `json:"phase,omitempty" extensions:"x-nullable" enums:"commentary,final_answer"`
	Content           []ItemContent    `json:"content,omitempty"`
	Command           string           `json:"command,omitempty"`
	Cwd               *string          `json:"cwd,omitempty" extensions:"x-nullable"`
	DurationMS        *int64           `json:"duration_ms,omitempty" extensions:"x-nullable"`
	ExitCode          *int64           `json:"exit_code,omitempty" extensions:"x-nullable"`
	Name              string           `json:"name,omitempty"`
	CallID            string           `json:"call_id,omitempty"`
	ServerLabel       string           `json:"server_label,omitempty"`
	Arguments         any              `json:"arguments,omitempty"`
	Output            any              `json:"output,omitempty" extensions:"x-nullable"`
	Error             any              `json:"error,omitempty" extensions:"x-nullable"`
	Action            *WebSearchAction `json:"action,omitempty" extensions:"x-nullable"`
	AgentID           string           `json:"agent_id,omitempty"`
	SenderAgentID     string           `json:"sender_agent_id,omitempty"`
	RecipientAgentID  string           `json:"recipient_agent_id,omitempty"`
	RecipientAgentIDs []string         `json:"recipient_agent_ids,omitempty"`
	Model             *string          `json:"model,omitempty" extensions:"x-nullable"`
	ReasoningEffort   *string          `json:"reasoning_effort,omitempty" extensions:"x-nullable"`
	Summary           []SummaryText    `json:"summary,omitempty"`
}

// ItemContent projects MessageContentResource, EncryptedContentResource.
type ItemContent struct {
	Type             string  `json:"type" binding:"required" enums:"input_text,input_image,output_text,encrypted_content"`
	Text             *string `json:"text,omitempty"`
	ImageURL         string  `json:"image_url,omitempty"`
	EncryptedContent *string `json:"encrypted_content,omitempty"`
}

// ItemList projects SessionItemListResource.
type ItemList struct {
	Object  string  `json:"object" binding:"required" enums:"list"`
	FirstID *string `json:"first_id" binding:"required" extensions:"x-nullable"`
	LastID  *string `json:"last_id" binding:"required" extensions:"x-nullable"`
	Data    []Item  `json:"data" binding:"required"`
	HasMore bool    `json:"has_more" binding:"required"`
}

// MCPHTTPTransport projects PersistedMcpTransportConfigParamHttp.
type MCPHTTPTransport struct {
	Type      string             `json:"type" binding:"required" enums:"http"`
	ServerURL string             `json:"server_url" binding:"required"`
	Headers   *map[string]string `json:"headers,omitempty" extensions:"x-nullable"`
}

// MCPTool projects AgentToolResourceMcp.
type MCPTool struct {
	Type             string                     `json:"type" binding:"required" enums:"mcp"`
	ServerLabel      string                     `json:"server_label" binding:"required"`
	Transport        MCPHTTPTransport           `json:"transport" binding:"required"`
	AllowedTools     *[]string                  `json:"allowed_tools" binding:"required" extensions:"x-nullable"`
	ConnectionOrigin string                     `json:"connection_origin" binding:"required" enums:"service,environment"`
	CredentialID     *string                    `json:"credential_id" binding:"required" extensions:"x-nullable"`
	RequestMetadata  map[string]json.RawMessage `json:"request_metadata" binding:"required" swaggertype:"object"`
	Required         bool                       `json:"required" binding:"required"`
}

// MCPToolInput projects AgentToolConfigParamMcp.
type MCPToolInput struct {
	Type             string          `json:"type" binding:"required" enums:"mcp"`
	ServerLabel      *string         `json:"server_label" binding:"required"`
	Transport        json.RawMessage `json:"transport" binding:"required" swaggertype:"object"`
	AllowedTools     json.RawMessage `json:"allowed_tools" extensions:"x-nullable" swaggertype:"object"`
	ConnectionOrigin *string         `json:"connection_origin" extensions:"x-nullable" enums:"service,environment"`
	CredentialID     *string         `json:"credential_id" extensions:"x-nullable"`
	RequestMetadata  json.RawMessage `json:"request_metadata" extensions:"x-nullable" swaggertype:"object"`
	Required         json.RawMessage `json:"required" swaggertype:"object"`
}

// MultiAgentConfig projects MultiAgentConfigResource.
type MultiAgentConfig struct {
	Enabled                bool `json:"enabled" binding:"required"`
	MaxConcurrentSubagents *int `json:"max_concurrent_subagents" binding:"required" extensions:"x-nullable"`
}

// OAuthCredentialRefresh projects McpOauthRefreshResource.
type OAuthCredentialRefresh struct {
	ClientID          string            `json:"client_id" binding:"required"`
	TokenEndpoint     string            `json:"token_endpoint" binding:"required"`
	TokenEndpointAuth OAuthEndpointAuth `json:"token_endpoint_auth" binding:"required"`
	Resource          *string           `json:"resource" binding:"required" extensions:"x-nullable"`
	Scope             *string           `json:"scope" binding:"required" extensions:"x-nullable"`
}

// OAuthCredentialRefreshInput projects CreateMcpOauthRefreshParam.
type OAuthCredentialRefreshInput struct {
	ClientID          *string                 `json:"client_id" binding:"required"`
	RefreshToken      *string                 `json:"refresh_token" binding:"required"`
	TokenEndpoint     *string                 `json:"token_endpoint" binding:"required"`
	TokenEndpointAuth *OAuthEndpointAuthInput `json:"token_endpoint_auth" binding:"required"`
	Resource          *string                 `json:"resource,omitempty" extensions:"x-nullable"`
	Scope             *string                 `json:"scope,omitempty" extensions:"x-nullable"`
}

// OAuthCredentialRefreshReplacement projects RotateMcpOauthRefreshParam.
type OAuthCredentialRefreshReplacement struct {
	RefreshToken      *string                       `json:"refresh_token,omitempty" extensions:"x-nullable"`
	Scope             json.RawMessage               `json:"scope,omitempty" extensions:"x-nullable" swaggertype:"object"`
	TokenEndpointAuth *OAuthEndpointAuthReplacement `json:"token_endpoint_auth,omitempty" extensions:"x-nullable"`
}

// OAuthEndpointAuth projects McpOauthTokenEndpointAuthResource.
type OAuthEndpointAuth struct {
	Type string `json:"type" binding:"required" enums:"none,client_secret_basic,client_secret_post"`
}

// OAuthEndpointAuthInput projects CreateMcpOauthTokenEndpointAuthParam.
type OAuthEndpointAuthInput struct {
	Type         string  `json:"type" binding:"required" enums:"none,client_secret_basic,client_secret_post"`
	ClientSecret *string `json:"client_secret,omitempty"`
}

// OAuthEndpointAuthReplacement projects RotateMcpOauthTokenEndpointAuthParam.
type OAuthEndpointAuthReplacement struct {
	Type         string  `json:"type" binding:"required" enums:"client_secret_basic,client_secret_post"`
	ClientSecret *string `json:"client_secret,omitempty" extensions:"x-nullable"`
}

// OutputTokenDetails projects OutputTokensDetailsResource.
type OutputTokenDetails struct {
	ReasoningTokens int64 `json:"reasoning_tokens" binding:"required"`
}

// Reasoning projects ReasoningParam.
type Reasoning struct {
	Effort  *string `json:"effort,omitempty" extensions:"x-nullable" enums:"none,minimal,low,medium,high,xhigh,max"`
	Summary *string `json:"summary,omitempty" extensions:"x-nullable" enums:"concise,detailed,auto"`
}

// ReasoningItem projects ReasoningItemResource.
type ReasoningItem struct {
	ID      string        `json:"id" binding:"required"`
	TurnID  string        `json:"turn_id" binding:"required"`
	Type    string        `json:"type" binding:"required" enums:"reasoning"`
	Status  *string       `json:"status" binding:"required" extensions:"x-nullable" enums:"in_progress,completed,incomplete"`
	Summary []SummaryText `json:"summary" binding:"required"`
}

// RequiredAction projects SessionRequiredActionResource.
type RequiredAction struct {
	Type          string `json:"type" binding:"required" enums:"function_call,environment_connection"`
	Arguments     any    `json:"arguments,omitempty"`
	CallID        string `json:"call_id,omitempty"`
	Name          string `json:"name,omitempty"`
	TurnID        string `json:"turn_id,omitempty"`
	EnvironmentID string `json:"environment_id,omitempty"`
}

// SavedAgent projects AgentResource.
type SavedAgent struct {
	SavedAgentConfiguration
	ID        string            `json:"id" binding:"required"`
	Object    string            `json:"object" binding:"required" enums:"agent"`
	Metadata  map[string]string `json:"metadata" binding:"required"`
	CreatedAt int64             `json:"created_at" binding:"required"`
	UpdatedAt int64             `json:"updated_at" binding:"required"`
}

// SavedAgentConfiguration projects AgentResource.
type SavedAgentConfiguration struct {
	XAgentsCore  *SavedAgentCore   `json:"x_agents_core,omitempty"`
	Model        string            `json:"model" binding:"required"`
	Name         *string           `json:"name" binding:"required" extensions:"x-nullable"`
	Instructions *string           `json:"instructions" binding:"required" extensions:"x-nullable"`
	MultiAgent   MultiAgentConfig  `json:"multi_agent" binding:"required"`
	Reasoning    Reasoning         `json:"reasoning" binding:"required"`
	ServiceTier  string            `json:"service_tier" binding:"required" enums:"auto,default,flex,priority,fast"`
	Text         TextConfig        `json:"text" binding:"required"`
	Tools        []json.RawMessage `json:"tools" binding:"required" swaggertype:"array,object"`
}

// SavedAgentList projects AgentListResource.
type SavedAgentList struct {
	Object  string       `json:"object" binding:"required" enums:"list"`
	Data    []SavedAgent `json:"data" binding:"required"`
	HasMore bool         `json:"has_more" binding:"required"`
	FirstID *string      `json:"first_id" binding:"required" extensions:"x-nullable"`
	LastID  *string      `json:"last_id" binding:"required" extensions:"x-nullable"`
}

// SendSubagentInputCallItem projects SendSubagentInputCallItemResource.
type SendSubagentInputCallItem struct {
	ID               string         `json:"id" binding:"required"`
	TurnID           string         `json:"turn_id" binding:"required"`
	Type             string         `json:"type" binding:"required" enums:"send_subagent_input_call"`
	Status           string         `json:"status" binding:"required" enums:"in_progress,completed,failed,incomplete"`
	SenderAgentID    string         `json:"sender_agent_id" binding:"required"`
	RecipientAgentID string         `json:"recipient_agent_id" binding:"required"`
	Content          []AgentContent `json:"content" binding:"required"`
}

// Session projects SessionResource.
type Session struct {
	XAgentsCore     *SessionCore       `json:"x_agents_core,omitempty"`
	ID              string             `json:"id" binding:"required"`
	Agent           Agent              `json:"agent" binding:"required"`
	CreatedAt       int64              `json:"created_at" binding:"required"`
	Environment     SessionEnvironment `json:"environment" binding:"required"`
	Error           *string            `json:"error" binding:"required" extensions:"x-nullable"`
	LastActiveAt    int64              `json:"last_active_at" binding:"required"`
	Metadata        map[string]string  `json:"metadata" binding:"required"`
	Object          string             `json:"object" binding:"required" enums:"agent.session"`
	RequiredActions []RequiredAction   `json:"required_actions" binding:"required"`
	Status          string             `json:"status" binding:"required" enums:"idle,in_progress,requires_action,failed"`
	Usage           *TokenUsage        `json:"usage" binding:"required" extensions:"x-nullable"`
	VaultIDs        []string           `json:"vault_ids" binding:"required"`
}

// SessionArtifact projects SessionArtifactResource.
type SessionArtifact struct {
	ID            string `json:"id" binding:"required"`
	CreatedAt     int64  `json:"created_at" binding:"required"`
	EnvironmentID string `json:"environment_id" binding:"required"`
	Object        string `json:"object" binding:"required" enums:"agent.session.artifact"`
	Path          string `json:"path" binding:"required"`
	SessionID     string `json:"session_id" binding:"required"`
	SizeBytes     int64  `json:"size_bytes" binding:"required"`
	TurnID        string `json:"turn_id" binding:"required"`
}

// SessionArtifactDeleted projects DeletedSessionArtifactResource.
type SessionArtifactDeleted struct {
	ID      string `json:"id" binding:"required"`
	Object  string `json:"object" binding:"required" enums:"agent.session.artifact.deleted"`
	Deleted bool   `json:"deleted" binding:"required"`
}

// SessionArtifactList projects SessionArtifactListResource.
type SessionArtifactList struct {
	Object  string            `json:"object" binding:"required" enums:"list"`
	FirstID *string           `json:"first_id" binding:"required" extensions:"x-nullable"`
	LastID  *string           `json:"last_id" binding:"required" extensions:"x-nullable"`
	Data    []SessionArtifact `json:"data" binding:"required"`
	HasMore bool              `json:"has_more" binding:"required"`
}

// SessionDeleted projects DeletedSessionResource.
type SessionDeleted struct {
	ID      string `json:"id" binding:"required"`
	Deleted bool   `json:"deleted" binding:"required"`
	Object  string `json:"object" binding:"required" enums:"agent.session.deleted"`
}

// SessionEnvironment projects EnvironmentResource.
type SessionEnvironment struct {
	Type                  string                       `json:"type" binding:"required" enums:"none,openai_hosted,self_hosted"`
	ID                    string                       `json:"id,omitempty"`
	CapabilityDirectories *[]string                    `json:"capability_directories,omitempty"`
	RemoteURL             string                       `json:"remote_url,omitempty"`
	WorkspaceDirectory    string                       `json:"workspace_directory,omitempty"`
	Network               *EnvironmentNetwork          `json:"network,omitempty"`
	Packages              *EnvironmentPackagesResponse `json:"packages,omitempty"`
	Files                 *[]json.RawMessage           `json:"files,omitempty" swaggertype:"array,object"`
	Plugins               *[]json.RawMessage           `json:"plugins,omitempty" swaggertype:"array,object"`
	Skills                *[]json.RawMessage           `json:"skills,omitempty" swaggertype:"array,object"`
}

// SessionEnvironmentState projects SessionEnvironmentStateResource.
type SessionEnvironmentState struct {
	ID     string       `json:"id" binding:"required"`
	Type   string       `json:"type" binding:"required"`
	Status string       `json:"status" binding:"required" enums:"pending,ready,connected,disconnected,failed"`
	Error  *StreamError `json:"error" binding:"required" extensions:"x-nullable"`
}

// SessionEvent projects SessionEvent.
type SessionEvent struct {
	Subagent     *Subagent                `json:"subagent,omitempty"`
	Type         string                   `json:"type" binding:"required" enums:"error,agent.session.environment.ready,agent.output.command_execution_output.delta,agent.session.created,agent.session.turn.created,agent.session.turn.in_progress,agent.session.turn.completed,agent.session.turn.failed,agent.session.turn.cancelled,agent.session.turn.item.added,agent.session.idle,agent.session.in_progress,agent.session.requires_action,agent.session.failed,agent.session.environment.pending,agent.session.environment.connected,agent.session.environment.disconnected,agent.session.environment.failed,agent.session.subagent.created,agent.session.subagent.active,agent.session.subagent.closed,agent.session.turn.item.done,agent.session.turn.content_part.added,agent.session.turn.content_part.done,agent.session.turn.output_text.delta,agent.session.turn.output_text.done,agent.session.turn.reasoning_summary_part.added,agent.session.turn.reasoning_summary_part.done,agent.session.turn.reasoning_summary_text.delta,agent.session.turn.reasoning_summary_text.done"`
	EventID      string                   `json:"event_id" binding:"required"`
	SessionID    string                   `json:"session_id,omitempty"`
	TurnID       string                   `json:"turn_id,omitempty" extensions:"x-nullable"`
	Session      *Session                 `json:"session,omitempty"`
	Turn         *Turn                    `json:"turn,omitempty"`
	Item         *Item                    `json:"item,omitempty"`
	ItemID       string                   `json:"item_id,omitempty"`
	OutputIndex  *int32                   `json:"output_index,omitempty" extensions:"x-nullable"`
	ContentIndex *int                     `json:"content_index,omitempty"`
	Part         *ItemContent             `json:"part,omitempty"`
	Delta        *string                  `json:"delta,omitempty"`
	Text         *string                  `json:"text,omitempty"`
	Error        *StreamError             `json:"error,omitempty"`
	Environment  *SessionEnvironmentState `json:"environment,omitempty"`
	Usage        *TokenUsage              `json:"usage,omitempty" extensions:"x-nullable"`
	SummaryIndex *int64                   `json:"summary_index,omitempty"`
	Status       *string                  `json:"status,omitempty" extensions:"x-nullable" enums:"incomplete"`
}

// SessionInput projects SessionInputParam.
type SessionInput struct {
	Type    string          `json:"type" binding:"required" enums:"agent.session.input.message,agent.session.input.cancel,agent.session.input.tool_result"`
	Input   []InputMessage  `json:"input,omitempty"`
	CallID  string          `json:"call_id,omitempty"`
	TurnID  string          `json:"turn_id,omitempty"`
	Success *bool           `json:"success,omitempty"`
	Error   json.RawMessage `json:"error,omitempty" extensions:"x-nullable" swaggertype:"object"`
	Output  any             `json:"output,omitempty" extensions:"x-nullable"`
}

// SessionList projects SessionListResource.
type SessionList struct {
	Object  string    `json:"object" binding:"required" enums:"list"`
	FirstID *string   `json:"first_id" binding:"required" extensions:"x-nullable"`
	LastID  *string   `json:"last_id" binding:"required" extensions:"x-nullable"`
	Data    []Session `json:"data" binding:"required"`
	HasMore bool      `json:"has_more" binding:"required"`
}

// Skill projects SkillResource.
type Skill struct {
	ID             string `json:"id" binding:"required"`
	Object         string `json:"object" binding:"required" enums:"skill"`
	CreatedAt      int64  `json:"created_at" binding:"required"`
	Name           string `json:"name" binding:"required"`
	Description    string `json:"description" binding:"required"`
	DefaultVersion string `json:"default_version" binding:"required"`
	LatestVersion  string `json:"latest_version" binding:"required"`
}

// SkillDeleted projects DeletedSkillResource.
type SkillDeleted struct {
	ID      string `json:"id" binding:"required"`
	Object  string `json:"object" binding:"required" enums:"skill.deleted"`
	Deleted bool   `json:"deleted" binding:"required"`
}

// SkillList projects SkillListResource.
type SkillList struct {
	Object  string  `json:"object" binding:"required" enums:"list"`
	Data    []Skill `json:"data" binding:"required"`
	FirstID *string `json:"first_id" binding:"required" extensions:"x-nullable"`
	LastID  *string `json:"last_id" binding:"required" extensions:"x-nullable"`
	HasMore bool    `json:"has_more" binding:"required"`
}

// SkillUpdateRequest projects SetDefaultSkillVersionBody.
type SkillUpdateRequest struct {
	DefaultVersion string `json:"default_version" binding:"required"`
}

// SkillVersion projects SkillVersionResource.
type SkillVersion struct {
	ID          string `json:"id" binding:"required"`
	Object      string `json:"object" binding:"required" enums:"skill.version"`
	CreatedAt   int64  `json:"created_at" binding:"required"`
	SkillID     string `json:"skill_id" binding:"required"`
	Version     string `json:"version" binding:"required"`
	Name        string `json:"name" binding:"required"`
	Description string `json:"description" binding:"required"`
}

// SkillVersionDeleted projects DeletedSkillVersionResource.
type SkillVersionDeleted struct {
	ID      string `json:"id" binding:"required"`
	Object  string `json:"object" binding:"required" enums:"skill.version.deleted"`
	Version string `json:"version" binding:"required"`
	Deleted bool   `json:"deleted" binding:"required"`
}

// SkillVersionList projects SkillVersionListResource.
type SkillVersionList struct {
	Object  string         `json:"object" binding:"required" enums:"list"`
	Data    []SkillVersion `json:"data" binding:"required"`
	FirstID *string        `json:"first_id" binding:"required" extensions:"x-nullable"`
	LastID  *string        `json:"last_id" binding:"required" extensions:"x-nullable"`
	HasMore bool           `json:"has_more" binding:"required"`
}

// SourceFile projects OpenAIFile.
type SourceFile struct {
	ID            string  `json:"id" binding:"required"`
	Object        string  `json:"object" binding:"required" enums:"file"`
	Bytes         int64   `json:"bytes" binding:"required"`
	CreatedAt     int64   `json:"created_at" binding:"required"`
	Filename      string  `json:"filename" binding:"required"`
	Purpose       string  `json:"purpose" binding:"required" enums:"assistants,assistants_output,batch,batch_output,fine-tune,fine-tune-results,vision,user_data"`
	Status        string  `json:"status" binding:"required" enums:"uploaded,processed,error"`
	ExpiresAt     *int64  `json:"expires_at"`
	StatusDetails *string `json:"status_details"`
}

// SourceFileDeleted projects DeleteFileResponse.
type SourceFileDeleted struct {
	ID      string `json:"id" binding:"required"`
	Object  string `json:"object" binding:"required" enums:"file"`
	Deleted bool   `json:"deleted" binding:"required"`
}

// SourceFileList projects ListFilesResponse.
type SourceFileList struct {
	Object  string       `json:"object" binding:"required"`
	Data    []SourceFile `json:"data" binding:"required"`
	HasMore bool         `json:"has_more" binding:"required"`
	FirstID *string      `json:"first_id" binding:"required"`
	LastID  *string      `json:"last_id" binding:"required"`
}

// StreamError projects SessionErrorResource.
type StreamError struct {
	Code    string  `json:"code" binding:"required" extensions:"x-nullable"`
	Type    string  `json:"type" binding:"required"`
	Message string  `json:"message" binding:"required"`
	Param   *string `json:"param,omitempty" binding:"required" extensions:"x-nullable"`
}

// Subagent projects SubagentResource.
type Subagent struct {
	ID            string         `json:"id" binding:"required"`
	Object        string         `json:"object" binding:"required" enums:"agent.session.subagent"`
	SessionID     string         `json:"session_id" binding:"required"`
	ParentAgentID string         `json:"parent_agent_id" binding:"required"`
	OpenedAt      int64          `json:"opened_at" binding:"required"`
	ClosedAt      *int64         `json:"closed_at" binding:"required" extensions:"x-nullable"`
	Name          *string        `json:"name" binding:"required" extensions:"x-nullable"`
	Instructions  []AgentContent `json:"instructions" binding:"required" extensions:"x-nullable"`
	Status        string         `json:"status" binding:"required" enums:"active,closed"`
}

// SubagentControlCallItem projects ResumeSubagentCallItemResource, InterruptSubagentCallItemResource, CloseSubagentCallItemResource.
type SubagentControlCallItem struct {
	ID               string `json:"id" binding:"required"`
	TurnID           string `json:"turn_id" binding:"required"`
	Type             string `json:"type" binding:"required" enums:"resume_subagent_call,interrupt_subagent_call,close_subagent_call"`
	Status           string `json:"status" binding:"required" enums:"in_progress,completed,failed,incomplete"`
	SenderAgentID    string `json:"sender_agent_id" binding:"required"`
	RecipientAgentID string `json:"recipient_agent_id" binding:"required"`
}

// SubagentList projects schema.
type SubagentList struct {
	Object  string     `json:"object" binding:"required" enums:"list"`
	FirstID *string    `json:"first_id" binding:"required" extensions:"x-nullable"`
	LastID  *string    `json:"last_id" binding:"required" extensions:"x-nullable"`
	Data    []Subagent `json:"data" binding:"required"`
	HasMore bool       `json:"has_more" binding:"required"`
}

// SummaryText projects SummaryTextResource.
type SummaryText struct {
	Type string `json:"type" binding:"required" enums:"summary_text"`
	Text string `json:"text" binding:"required"`
}

// TextConfig projects TextResource.
type TextConfig struct {
	Format    TextFormat `json:"format" binding:"required"`
	Verbosity string     `json:"verbosity" binding:"required" enums:"low,medium,high"`
}

// TextConfigInput projects TextParam.
type TextConfigInput struct {
	Format    json.RawMessage `json:"format,omitempty" extensions:"x-nullable" swaggertype:"object"`
	Verbosity *string         `json:"verbosity,omitempty" extensions:"x-nullable" enums:"low,medium,high"`
}

// TextFormat projects TextFormatResource.
type TextFormat struct {
	Type   string          `json:"type" binding:"required" enums:"text,json_schema"`
	Schema json.RawMessage `json:"schema,omitempty" swaggertype:"object"`
}

// TokenUsage projects TokenUsageResource.
type TokenUsage struct {
	InputTokens         int64              `json:"input_tokens" binding:"required"`
	InputTokensDetails  InputTokenDetails  `json:"input_tokens_details" binding:"required"`
	OutputTokens        int64              `json:"output_tokens" binding:"required"`
	OutputTokensDetails OutputTokenDetails `json:"output_tokens_details" binding:"required"`
	TotalTokens         int64              `json:"total_tokens" binding:"required"`
}

// Turn projects TurnResource.
type Turn struct {
	ID          string      `json:"id" binding:"required"`
	AgentID     string      `json:"agent_id" binding:"required"`
	SubagentID  *string     `json:"subagent_id" binding:"required" extensions:"x-nullable"`
	SessionID   string      `json:"session_id" binding:"required"`
	Object      string      `json:"object" binding:"required" enums:"agent.session.turn"`
	Status      string      `json:"status" binding:"required" enums:"queued,in_progress,waiting,completed,failed,cancelled"`
	CreatedAt   int64       `json:"created_at" binding:"required"`
	StartedAt   *int64      `json:"started_at" binding:"required" extensions:"x-nullable"`
	CompletedAt *int64      `json:"completed_at" binding:"required" extensions:"x-nullable"`
	Error       *TurnError  `json:"error" binding:"required" extensions:"x-nullable"`
	Usage       *TokenUsage `json:"usage" binding:"required" extensions:"x-nullable"`
}

// TurnError projects SessionTurnErrorResource.
type TurnError struct {
	Code    string `json:"code" binding:"required" enums:"context_length_exceeded,session_budget_exceeded,usage_limit_exceeded,rate_limit_exceeded,server_overloaded,cyber_policy,connection_failed,server_error,authentication_error,invalid_request,resource_not_found,sandbox_error,executor_version_incompatible,active_turn_not_steerable,request_timeout,internal_error"`
	Message string `json:"message" binding:"required"`
}

// TurnList projects SessionTurnListResource.
type TurnList struct {
	Object  string  `json:"object" binding:"required" enums:"list"`
	FirstID *string `json:"first_id" binding:"required" extensions:"x-nullable"`
	LastID  *string `json:"last_id" binding:"required" extensions:"x-nullable"`
	Data    []Turn  `json:"data" binding:"required"`
	HasMore bool    `json:"has_more" binding:"required"`
}

// UpdateAgentRequest projects UpdateAgentParams.
type UpdateAgentRequest struct {
	XAgentsCore  *SavedAgentCoreInput `json:"x_agents_core,omitempty"`
	Model        *string              `json:"model,omitempty"`
	Name         *string              `json:"name,omitempty" extensions:"x-nullable"`
	Instructions *string              `json:"instructions,omitempty" extensions:"x-nullable"`
	Metadata     map[string]*string   `json:"metadata,omitempty" extensions:"x-nullable"`
	MultiAgent   json.RawMessage      `json:"multi_agent,omitempty" extensions:"x-nullable" swaggertype:"object"`
	Reasoning    *Reasoning           `json:"reasoning,omitempty" extensions:"x-nullable"`
	ServiceTier  *string              `json:"service_tier,omitempty" extensions:"x-nullable" enums:"auto,default,flex,priority,fast"`
	Text         *TextConfigInput     `json:"text,omitempty" extensions:"x-nullable"`
	Tools        []json.RawMessage    `json:"tools,omitempty" extensions:"x-nullable" swaggertype:"array,object"`
}

// Vault projects VaultResource.
type Vault struct {
	ID        string            `json:"id" binding:"required"`
	Object    string            `json:"object" binding:"required" enums:"vault"`
	CreatedAt int64             `json:"created_at" binding:"required"`
	Name      *string           `json:"name" binding:"required" extensions:"x-nullable"`
	Metadata  map[string]string `json:"metadata" binding:"required"`
}

// VaultDeleted projects DeletedVaultResource.
type VaultDeleted struct {
	ID      string `json:"id" binding:"required"`
	Deleted bool   `json:"deleted" binding:"required"`
	Object  string `json:"object" binding:"required" enums:"vault.deleted"`
}

// VaultList projects VaultListResource.
type VaultList struct {
	Object  string  `json:"object" binding:"required" enums:"list"`
	Data    []Vault `json:"data" binding:"required"`
	HasMore bool    `json:"has_more" binding:"required"`
	FirstID *string `json:"first_id" binding:"required" extensions:"x-nullable"`
	LastID  *string `json:"last_id" binding:"required" extensions:"x-nullable"`
}

// WaitForSubagentsCallItem projects WaitForSubagentsCallItemResource.
type WaitForSubagentsCallItem struct {
	ID                string   `json:"id" binding:"required"`
	TurnID            string   `json:"turn_id" binding:"required"`
	Type              string   `json:"type" binding:"required" enums:"wait_for_subagents_call"`
	Status            string   `json:"status" binding:"required" enums:"in_progress,completed,failed,incomplete"`
	SenderAgentID     string   `json:"sender_agent_id" binding:"required"`
	RecipientAgentIDs []string `json:"recipient_agent_ids" binding:"required"`
}

// WebSearchAction projects WebSearchActionResource.
type WebSearchAction struct {
	Type    string   `json:"type" binding:"required" enums:"search,open_page,find_in_page,other"`
	Query   *string  `json:"query,omitempty" extensions:"x-nullable"`
	Queries []string `json:"queries,omitempty" extensions:"x-nullable"`
	URL     *string  `json:"url,omitempty" extensions:"x-nullable"`
	Pattern *string  `json:"pattern,omitempty" extensions:"x-nullable"`
}

func (value WebSearchAction) MarshalJSON() ([]byte, error) {
	switch value.Type {
	case "search":
		return json.Marshal(struct {
			Type    string   `json:"type"`
			Query   *string  `json:"query"`
			Queries []string `json:"queries"`
		}{
			Type:    value.Type,
			Query:   value.Query,
			Queries: value.Queries,
		})
	case "open_page":
		return json.Marshal(struct {
			Type string  `json:"type"`
			URL  *string `json:"url"`
		}{
			Type: value.Type,
			URL:  value.URL,
		})
	case "find_in_page":
		return json.Marshal(struct {
			Type    string  `json:"type"`
			URL     *string `json:"url"`
			Pattern *string `json:"pattern"`
		}{
			Type:    value.Type,
			URL:     value.URL,
			Pattern: value.Pattern,
		})
	case "other":
		return json.Marshal(struct {
			Type string `json:"type"`
		}{
			Type: value.Type,
		})
	default:
		return nil, fmt.Errorf("invalid WebSearchAction type %q", value.Type)
	}
}

// reasoningResponse projects ReasoningResource.
type reasoningResponse struct {
	Effort  *string `json:"effort" binding:"required" extensions:"x-nullable" enums:"none,minimal,low,medium,high,xhigh,max"`
	Summary *string `json:"summary" binding:"required" extensions:"x-nullable" enums:"concise,detailed,auto"`
}

// sessionError projects SessionErrorResource.
type sessionError struct {
	Code    string  `json:"code" binding:"required" extensions:"x-nullable"`
	Type    string  `json:"type" binding:"required"`
	Message string  `json:"message" binding:"required"`
	Param   *string `json:"param" binding:"required" extensions:"x-nullable"`
}
